"""Single environment loading, defaulting, and validation boundary for Atlas."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Final

from dotenv import load_dotenv

PROJECT_ROOT: Final = Path(__file__).resolve().parents[2]
DEFAULT_REPOSITORY_ROOT: Final = PROJECT_ROOT / ".atlas" / "repository"

# Process-provided values win. The root file exists only for local development.
load_dotenv(PROJECT_ROOT / ".env", override=False)

DEFAULTS: Final[dict[str, str | None]] = {
    "ATLAS_API_URL": None,
    "DATABASE_URL": "postgresql://atlas:atlas@127.0.0.1:5432/atlas",
    "ATLAS_CATALOGUE_CATALOG": "postgres",
    "ATLAS_CATALOGUE_CATALOG_PATH": None,
    "ATLAS_CATALOGUE_CATALOG_DSN": "host=127.0.0.1 port=5432 dbname=atlas_catalogue user=atlas password=atlas",
    "ATLAS_CATALOGUE_ROOT": str(DEFAULT_REPOSITORY_ROOT),
    "ATLAS_CATALOGUE_ALIAS": "atlas",
    "ATLAS_CATALOGUE_SCHEMA": "main",
    "ATLAS_CATALOGUE_DUCKDB_DATABASE": ":memory:",
    "ATLAS_CATALOGUE_DUCKDB_THREADS": None,
    "ATLAS_CATALOGUE_DUCKDB_MEMORY_LIMIT": None,
    "ATLAS_CATALOGUE_DUCKDB_MAX_TEMP_SIZE": None,
    "ATLAS_CATALOGUE_DUCKDB_TEMP_DIRECTORY": None,
    "ATLAS_CATALOGUE_POSTGRES_POOL_MAX_CONNECTIONS": "2",
    "ATLAS_CATALOGUE_POSTGRES_POOL_IDLE_TIMEOUT_MS": "5000",
    "ATLAS_CATALOGUE_POSTGRES_POOL_MAX_LIFETIME_MS": "60000",
    "ATLAS_CATALOGUE_POSTGRES_POOL_WAIT_TIMEOUT_MS": "10000",
    "ATLAS_CATALOGUE_OVERRIDE_DATA_PATH": None,
    "ATLAS_CATALOGUE_DATA_INLINING_ROW_LIMIT": "0",
    "ATLAS_CATALOGUE_READ_POOL_SIZE": "2",
    "ATLAS_CATALOGUE_READ_THREADS": "2",
    "ATLAS_CATALOGUE_READ_POOL_WAIT_SECONDS": "5",
    "ATLAS_CATALOGUE_READ_MAX_ATTEMPTS": "3",
    "ATLAS_CATALOGUE_READ_RETRY_SECONDS": "0.1",
    "ATLAS_REPOSITORY_STORAGE": "disk",
    "ATLAS_REPOSITORY_ROOT": str(DEFAULT_REPOSITORY_ROOT),
    "ATLAS_REPOSITORY_S3_PREFIX": "",
    "ATLAS_REPOSITORY_S3_BUCKET": None,
    "ATLAS_REPOSITORY_S3_ENDPOINT": None,
    "ATLAS_REPOSITORY_S3_REGION": None,
    "ATLAS_REPOSITORY_S3_KEY_ID": None,
    "ATLAS_REPOSITORY_S3_SECRET_ACCESS_KEY": None,
    "ATLAS_REPOSITORY_S3_SESSION_TOKEN": None,
    "ATLAS_REPOSITORY_S3_URL_STYLE": None,
    "ATLAS_REPOSITORY_S3_USE_SSL": None,
    "ATLAS_REPOSITORY_STAGING_ROOT": None,
    "AWS_REGION": None,
    "AWS_ACCESS_KEY_ID": None,
    "AWS_SECRET_ACCESS_KEY": None,
    "AWS_SESSION_TOKEN": None,
    "ATLAS_REPOSITORY_MAX_HTML_BYTES": str(64 * 1024 * 1024),
    "ATLAS_REPOSITORY_MAX_DOCUMENT_ELEMENTS": "1000000",
    "ATLAS_REPOSITORY_MAX_DOCUMENT_STAGED_BYTES": str(256 * 1024 * 1024),
    "NATS_URL": "nats://127.0.0.1:4222",
    "NATS_RETENTION": "5m",
    "ATLAS_NATS_MAX_ENVELOPE_BYTES": str(900 * 1024),
    "ATLAS_INGEST_BATCH_ITEMS": "100",
    "ATLAS_INGEST_BATCH_ELEMENT_ROWS": "250000",
    "ATLAS_INGEST_BATCH_BYTES": str(256 * 1024 * 1024),
    "ATLAS_INGEST_BATCH_WAIT_SECONDS": "5",
    "ATLAS_INGEST_ACK_WAIT_SECONDS": "60",
    "ATLAS_INGEST_MAX_ACK_PENDING": "1000",
    "ATLAS_INGEST_MAX_DELIVER": "5",
    "ATLAS_INGEST_RESULT_POLL_SECONDS": "0.5",
    "ATLAS_INGEST_RESULT_TTL_SECONDS": str(7 * 24 * 60 * 60),
    "ATLAS_INGEST_RESULT_MAX_BYTES": str(256 * 1024 * 1024),
    "ATLAS_INGEST_RESULT_REPLICAS": "1",
    "ATLAS_CATALOGUE_WORK_STREAM_REPLICAS": "1",
    "ATLAS_DEAD_LETTER_TTL_SECONDS": str(30 * 24 * 60 * 60),
    "ATLAS_DEAD_LETTER_MAX_BYTES": str(256 * 1024 * 1024),
    "ATLAS_INGEST_STAGING_GRACE_SECONDS": "3600",
    "ATLAS_REPOSITORY_COMPACTION_INTERVAL_SECONDS": "300",
    "ATLAS_REPOSITORY_COMPACTION_MIN_FILES": "64",
    "ATLAS_REPOSITORY_COMPACTION_MAX_INPUT_FILE_BYTES": str(1024 * 1024),
    "ATLAS_REPOSITORY_COMPACTION_TARGET_FILE_BYTES": str(32 * 1024 * 1024),
    "ATLAS_REPOSITORY_COMPACTION_MAX_OUTPUT_FILES": "4",
    "ATLAS_REPOSITORY_COMPACTION_MAX_OPERATION_BYTES": str(256 * 1024 * 1024),
    "ATLAS_REPOSITORY_CLEANUP_OLD_FILES_SECONDS": str(7 * 24 * 60 * 60),
    "ATLAS_CRAWL_HTTP_WORKER_CONCURRENCY": "8",
    "ATLAS_CRAWL_HTTP_WORKER_ID": None,
    "ATLAS_CRAWL_HTTP_MAX_ACK_PENDING": "1000",
    "ATLAS_CRAWL_BROWSER_WORKER_CONCURRENCY": "1",
    "ATLAS_CRAWL_BROWSER_WORKER_ID": None,
    "ATLAS_CRAWL_BROWSER_MAX_ACK_PENDING": "100",
    "ATLAS_CRAWL_PROVIDER_WORKER_CONCURRENCY": "4",
    "ATLAS_CRAWL_PROVIDER_WORKER_ID": None,
    "ATLAS_CRAWL_PROVIDER_MAX_ACK_PENDING": "100",
    "ATLAS_GRAPH_MAX_REQUESTS_PER_RUN": "10000",
    "ATLAS_GRAPH_MAX_RUN_SECONDS": "3600",
    "ATLAS_GRAPH_STREAM_REPLICAS": "1",
    "ATLAS_GRAPH_ACK_WAIT_SECONDS": "60",
    "ATLAS_CRAWL_MAX_DELIVER": "5",
    "ATLAS_POLICY_TRIAL_SAMPLE_SHARE": "0",
    "ATLAS_POLICY_TRIAL_MAX_IN_FLIGHT": "100",
    "ATLAS_POLICY_TRIAL_SAMPLER_VERSION": "1",
    "ATLAS_POLICY_TRIAL_PROVIDER_ENABLED": "false",
    "ATLAS_GRAPH_STATE_MAX_BYTES": str(256 * 1024 * 1024),
    "ATLAS_GRAPH_PROGRESS_TTL_SECONDS": str(30 * 24 * 60 * 60),
    "ATLAS_NAVIGATION_MAX_PACKAGE_BYTES": str(16 * 1024 * 1024),
    "ATLAS_NAVIGATION_OBJECT_RETENTION_DAYS": "2",
    "ATLAS_NAVIGATION_CLEANUP_GRACE_SECONDS": "60",
    "ATLAS_EDGE_MAX_OUTPUT_ROWS": "100000",
    "ATLAS_EDGE_MAX_OUTPUT_BYTES": str(16 * 1024 * 1024),
    "ATLAS_EDGE_QUERY_MEMORY_LIMIT": "512MB",
    "ATLAS_EDGE_QUERY_TIMEOUT_SECONDS": "30",
    "ATLAS_CRAWL_WORKER_PRESENCE_TTL_SECONDS": "30",
    "ATLAS_INGESTION_WORKER_CONCURRENCY": "1",
    "ATLAS_CATALOG_OPERATION_LOCK_TIMEOUT_SECONDS": "60",
    "ATLAS_CATALOG_OPERATION_MAX_ATTEMPTS": "5",
    "ATLAS_CATALOG_OPERATION_RETRY_INITIAL_SECONDS": "0.1",
    "ATLAS_CATALOG_OPERATION_RETRY_MAX_SECONDS": "2",
    "ATLAS_CATALOG_OPERATION_LEASE_SECONDS": "30",
    "ATLAS_CATALOG_OPERATION_HEARTBEAT_SECONDS": "5",
    "ATLAS_CATALOG_OPERATION_ACQUIRE_TIMEOUT_SECONDS": "1",
    "ATLAS_CATALOG_OPERATION_LEASE_REPLICAS": "1",
    "ATLAS_RESOURCE_CATALOGUE_CAPACITY": "2",
    "ATLAS_RESOURCE_CATALOGUE_CRITICAL_RESERVE": "1",
    "ATLAS_RESOURCE_CATALOGUE_NONCRITICAL_RESERVE": "1",
    "ATLAS_RESOURCE_CATALOGUE_BACKFILL_MAX": "1",
    "ATLAS_RESOURCE_OBJECT_READ_CAPACITY": "32",
    "ATLAS_RESOURCE_OBJECT_WRITE_CAPACITY": "32",
    "ATLAS_RESOURCE_OBJECT_UNIT_BYTES": str(8 * 1024 * 1024),
    "ATLAS_RESOURCE_LEASE_SECONDS": "120",
    "ATLAS_RESOURCE_HEARTBEAT_SECONDS": "30",
    "ATLAS_RESOURCE_ACQUIRE_TIMEOUT_SECONDS": "10",
    "ATLAS_RESOURCE_LEASE_REPLICAS": "1",
    "ATLAS_BROWSER_CONCURRENCY": "1",
    "FIRECRAWL_API_KEY": None,
    "ATLAS_CACHE_MAX_AGE_SECONDS": "120",
    "ATLAS_CACHE_STALE_IF_ERROR_SECONDS": None,
    "ATLAS_LOG_LEVEL": "INFO",
    "ATLAS_METRICS_ENABLED": "true",
    "ATLAS_METRICS_HOST": "0.0.0.0",
    "ATLAS_WORKER_QUEUE_STALL_SECONDS": "300",
    "ATLAS_ACQUISITION_WORKER_HEALTH_HOST": "0.0.0.0",
    "ATLAS_ACQUISITION_WORKER_HEALTH_PORT": "9099",
    "ATLAS_ACQUISITION_WORKER_HEALTH_HEARTBEAT_TIMEOUT_SECONDS": "10",
    "ATLAS_CRAWL_HTTP_WORKER_METRICS_PORT": "9090",
    "ATLAS_CRAWL_BROWSER_WORKER_METRICS_PORT": "9097",
    "ATLAS_CRAWL_PROVIDER_WORKER_METRICS_PORT": "9098",
    "ATLAS_INGESTION_WORKER_METRICS_PORT": "9091",
    "ATLAS_INGESTION_WORKER_HEALTH_HOST": "0.0.0.0",
    "ATLAS_INGESTION_WORKER_HEALTH_PORT": "9092",
    "ATLAS_INGESTION_WORKER_HEALTH_HEARTBEAT_TIMEOUT_SECONDS": "5",
    "ATLAS_INGESTION_WORKER_HEALTH_PROBE_INTERVAL_SECONDS": "10",
    "ATLAS_INGESTION_WORKER_HEALTH_PROBE_TIMEOUT_SECONDS": "2",
    "ATLAS_MATERIALIZATION_WORKER_METRICS_PORT": "9093",
    "ATLAS_MATERIALIZATION_WORKER_HEALTH_HOST": "0.0.0.0",
    "ATLAS_MATERIALIZATION_WORKER_HEALTH_PORT": "9096",
    "ATLAS_MATERIALIZATION_WORKER_HEALTH_HEARTBEAT_TIMEOUT_SECONDS": "5",
    "ATLAS_MATERIALIZATION_WORKER_HEALTH_PROBE_INTERVAL_SECONDS": "10",
    "ATLAS_MATERIALIZATION_WORKER_HEALTH_PROBE_TIMEOUT_SECONDS": "2",
    "ATLAS_MAINTENANCE_WORKER_METRICS_PORT": "9094",
    "ATLAS_MAINTENANCE_WORKER_HEALTH_HOST": "0.0.0.0",
    "ATLAS_MAINTENANCE_WORKER_HEALTH_PORT": "9095",
    "ATLAS_MAINTENANCE_WORKER_HEALTH_HEARTBEAT_TIMEOUT_SECONDS": "5",
    "ATLAS_MATERIALIZATION_MAX_OUTPUT_ROWS": "100000",
    "ATLAS_MATERIALIZATION_MAX_OUTPUT_BYTES": str(32 * 1024 * 1024),
    "ATLAS_MATERIALIZATION_BACKFILL_PAGE_SIZE": "1000",
    "ATLAS_MATERIALIZATION_BACKFILL_SCOPES_PER_MINUTE": "60",
    "ATLAS_MATERIALIZATION_ACK_WAIT_SECONDS": "60",
    "ATLAS_MATERIALIZATION_MAX_DELIVER": "5",
    "ATLAS_DUCKLAKE_CDC_VERSION": "ducklake_cdc 0.5.3",
    "ATLAS_DUCKLAKE_CDC_EXTENSION": "",
    "ATLAS_DUCKLAKE_CDC_BUILD_REVISION": "3d41ff7",
}


class ConfigurationError(ValueError):
    """An Atlas setting is missing or invalid."""


def get_optional(name: str) -> str | None:
    _assert_known(name)
    value = os.getenv(name, DEFAULTS[name])
    return value.strip() if value is not None and value.strip() else None


def get_str(name: str) -> str:
    value = get_optional(name)
    if value is None:
        raise ConfigurationError(f"{name} is required")
    return value


def get_int(name: str, *, minimum: int | None = 1) -> int:
    raw = get_str(name)
    try:
        value = int(raw)
    except ValueError as exc:
        raise ConfigurationError(f"{name} must be an integer") from exc
    if minimum is not None and value < minimum:
        raise ConfigurationError(f"{name} must be at least {minimum}")
    return value


def get_float(name: str, *, minimum: float | None = 0.0, exclusive: bool = True) -> float:
    raw = get_str(name)
    try:
        value = float(raw)
    except ValueError as exc:
        raise ConfigurationError(f"{name} must be a number") from exc
    if minimum is not None and (value <= minimum if exclusive else value < minimum):
        qualifier = "greater than" if exclusive else "at least"
        raise ConfigurationError(f"{name} must be {qualifier} {minimum}")
    return value


def get_bool(name: str) -> bool:
    value = get_str(name).lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off"}:
        return False
    raise ConfigurationError(f"{name} must be a boolean")


def get_path(name: str) -> Path:
    return Path(get_str(name)).expanduser()


def _assert_known(name: str) -> None:
    if name not in DEFAULTS:
        raise ConfigurationError(f"Unknown Atlas setting: {name}")
