import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { toast } from "sonner"
import { apiErrorFromResponse, apiUrl, extractApiError } from "@/lib/api"
import type { MaterializedViewList, MaterializedViewRecord } from "@/types/catalogue"
const key = ["materialized-views"] as const
async function json<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(apiUrl(path), init); if (!response.ok) throw await apiErrorFromResponse(response); return response.json() as Promise<T> }
export function useMaterializedViews() { return useQuery({ queryKey: key, queryFn: () => json<MaterializedViewList>("/materialized-views/") }) }
export function useCreateMaterializedView() { const client = useQueryClient(); return useMutation({ mutationFn: (input: { name: string; display_name?: string; description?: string; query_revision_id: string }) => json<MaterializedViewRecord>("/materialized-views/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }), onSuccess: () => { void client.invalidateQueries({ queryKey: key }); toast.success("Materialized view created.") }, onError: (error) => toast.error(extractApiError(error)) }) }
export function useRefreshMaterializedView() { const client = useQueryClient(); return useMutation({ mutationFn: (view: MaterializedViewRecord) => json<MaterializedViewRecord>(`/materialized-views/${view.id}/refresh`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expected_ducklake_table_uuid: view.ducklake_table_uuid }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: key }); toast.success("Materialized view refreshed.") }, onError: (error) => toast.error(extractApiError(error)) }) }
export function useDropMaterializedView() { const client = useQueryClient(); return useMutation({ mutationFn: async (view: MaterializedViewRecord) => { const params = new URLSearchParams({ expected_ducklake_table_uuid: view.ducklake_table_uuid }); const response = await fetch(apiUrl(`/materialized-views/${view.id}?${params}`), { method: "DELETE" }); if (!response.ok) throw await apiErrorFromResponse(response) }, onSuccess: () => { void client.invalidateQueries({ queryKey: key }); toast.success("Materialized view dropped.") }, onError: (error) => toast.error(extractApiError(error)) }) }
