import type { Metadata } from "next"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import { buttonVariants } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { HtmlStructureIllustration } from "@/components/illustrations/html-structure"
import { TextPlacementIllustration } from "@/components/illustrations/text-placement"
import { featuredDataset } from "@/lib/datasets"
import { SqlEditor } from "@/components/sql-editor"
import { schemaReference, sqlDraftLink } from "@/lib/schema-reference"

export const metadata: Metadata = { title: "Documentation", description: "Build a dataset from collected web pages. Learn the collection model, public schema, join keys, SQL extraction patterns, and query limits." }

const quickStart = `SELECT requested_url, observed_at, outcome, content_id
FROM web.observation
ORDER BY observed_at DESC NULLS LAST, observation_id
LIMIT 20;`
const headings = `WITH pages AS (
  SELECT observation_id, requested_url, content_id
  FROM web.observation
  WHERE content_id IS NOT NULL
  ORDER BY observed_at DESC NULLS LAST, observation_id
  LIMIT 10
)
SELECT p.requested_url, h.element_index,
       h.text_direct AS heading, h.attributes['class'] AS css_class
FROM pages p
JOIN content.html_element h USING (content_id)
WHERE h.tag = 'h1'
ORDER BY p.observation_id, h.element_index
LIMIT 100;`
const links = `WITH pages AS (
  SELECT observation_id
  FROM web.observation
  WHERE content_id IS NOT NULL
  ORDER BY observed_at DESC NULLS LAST, observation_id
  LIMIT 10
)
SELECT l.source_url, l.target_url, l.relation_scope
FROM pages p
JOIN web.link_occurrence l USING (observation_id)
ORDER BY l.source_url, l.element_index
LIMIT 100;`
const latest = `SELECT requested_url, observed_at, outcome, content_id
FROM web.observation
QUALIFY row_number() OVER (
  PARTITION BY requested_url
  ORDER BY observed_at DESC NULLS LAST, observation_id DESC
) = 1
ORDER BY requested_url
LIMIT 20;`

function Example({ title, description, sql }: { title: string; description: string; sql: string }) {
  return <Card><CardHeader><CardTitle><h3 className="font-medium">{title}</h3></CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="flex min-w-0 flex-col gap-4"><SqlEditor value={sql} readOnly /><Link className="story-link self-start" href={sqlDraftLink(sql)}>Open in SQL console →</Link></CardContent></Card>
}

export default function Page() {
  return <main className="mx-auto max-w-7xl px-5 pb-12 sm:px-8">
    <header className="flex flex-wrap items-baseline justify-between gap-2 py-6"><h1 className="text-xl font-medium">Documentation</h1><p className="text-sm text-muted-foreground">Schema reference, query examples, and dataset-building instructions.</p></header>
    <div className="grid items-start gap-8 lg:grid-cols-[220px_minmax(0,1fr)]">
    <aside className="lg:sticky lg:top-6 lg:max-h-[calc(100vh-3rem)] lg:overflow-y-auto">
      <nav aria-label="Documentation sections" className="flex flex-col gap-5">
        {[
          { title: "Get started", links: [["quick-start", "Run your first query"], ["how-it-works", "Collection and coverage"], ["building", "Build a dataset"]] },
          { title: "Guides", links: [["joins", "Identity and joins"], ["recipe", "Extract book listings"], ["examples", "SQL patterns"]] },
          { title: "Reference", links: [["schema", "Public schema"], ["macros", "Functions and macros"], ["limits", "Query limits and behavior"]] },
        ].map(group => <div key={group.title} className="flex flex-col gap-1"><CardDescription className="px-3"><strong>{group.title}</strong></CardDescription>{group.links.map(([id, label]) => <Link key={id} href={`#${id}`} className={buttonVariants({ variant: "ghost", size: "sm" }) + " justify-start whitespace-normal h-auto py-2"}>{label}</Link>)}</div>)}
        <Separator />
        <Link href="/sql" className={buttonVariants({ variant: "outline", size: "sm" })}>Open SQL console <ArrowUpRight aria-hidden="true" /></Link>
      </nav>
    </aside>
    <div className="flex min-w-0 flex-col gap-8">

    <section id="quick-start" aria-labelledby="quick-start-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="quick-start-heading">Run your first query</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Run this against the current corpus. Each row is an observation, so the same URL can appear more than once. Examples open as editable drafts and run when you choose.</p><Example title="Recent observations" description="Up to 20 observations, with dated observations first. Missing content and unsuccessful observations remain visible." sql={quickStart} /><p>Use two-part names such as <code>web.observation</code> in the SQL console. The fully qualified form is <code>periplus.web.observation</code>. <Link href="/observatory#coverage">Coverage</Link> shows which sites are represented today.</p></CardContent></Card></section>
    <section id="how-it-works" aria-labelledby="how-it-works-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="how-it-works-heading">Collection and coverage</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Periplus observes a page in a browser after configured loading and interaction steps; imports can bring content acquired elsewhere. That document records one observed state of a page, rather than every possible interactive or personalised state.</p><p>Periplus retains observed content immutably and shares identical byte sequences through content identities. It records observations, then builds HTML and link projections separately. Collection can finish before those projections are queryable.</p><p>Coverage includes selected sources and imports. It offers neither a representative sample of the web nor a uniform refresh schedule. Collection dates can be missing; the latest date for a site does not establish that all its pages are fresh.</p><p>Use the <Link href="/observatory">Observatory</Link> to request missing sources and inspect collection progress. A link found in a page does not mean its destination has been collected. Check available observations and projections before relying on a source in your dataset.</p><div className="about-actions"><Link className="story-link" href="/observatory#coverage">Inspect coverage <ArrowUpRight /></Link><Link className="story-link" href="/observatory">Suggest a starting point <ArrowUpRight /></Link></div></CardContent></Card></section>
    <section id="building" aria-labelledby="building-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="building-heading">Build a dataset</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><ol className="flex list-decimal flex-col gap-5 pl-5"><li><strong>Describe the dataset you need.</strong><p>In <Link href="/discover">Discover</Link>, describe what one row should represent, the columns you want, and the sources or population to include. The editable specification keeps those choices visible alongside the conversation.</p></li><li><strong>Check what the material supports.</strong><p>The agent explores the catalogue and uses SQL to test how source structure can fill your schema. Review the results and resolve choices that affect the dataset, such as which observation to use or how to handle missing prices. Missing sources need a collection request.</p></li><li><strong>Inspect and keep the result.</strong><p>Review the preview and validation evidence. Export returned rows as CSV and download the definition and SQL. Open the separate <Link href="/sql">SQL console</Link> to work directly with a query.</p></li></ol><h3 className="font-medium">What a rerun reproduces</h3><p>SQL preserves the extraction method. Reproducing identical rows also requires the same input data, schema, and deterministic semantics. A source snapshot reference records the input version; it does not pin a future rerun. Query links save SQL and parameters, not a frozen dataset.</p><p>The agent receives at most 20 sampled rows per query. Previews and CSV exports contain up to 1,000 returned rows, and the query may select a smaller input sample. Check the SQL and <Link href="#limits">result limits</Link> before treating a preview as complete. Download your work before reloading the temporary workspace.</p></CardContent></Card></section>


    <section id="joins" aria-labelledby="joins-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="joins-heading">Identity and joins</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Two URLs—or two visits to the same URL—can retain identical bytes. Those observations share a <code>content_id</code>. HTML structure is stored once for that content; joining it to observations repeats it for each matching observation.</p><Table><TableHeader><TableRow><TableHead>From → to</TableHead><TableHead>Join on</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Observation → content object</TableCell><TableCell><code>content_id</code></TableCell></TableRow><TableRow><TableCell>Observation → HTML elements</TableCell><TableCell><code>content_id</code></TableCell></TableRow><TableRow><TableCell>Observation → link occurrences</TableCell><TableCell><code>observation_id</code></TableCell></TableRow><TableRow><TableCell>Link occurrence → HTML element</TableCell><TableCell><code>content_id + element_index</code></TableCell></TableRow></TableBody></Table><p>Use a LEFT JOIN to retain observations without matching content or structure. An INNER JOIN keeps only matches. Counting joined HTML rows counts elements, not pages; choose distinct URLs, observation IDs, or content IDs according to your question.</p><Alert><AlertDescription>Link resolution belongs to an observation. Join links on observation_id to preserve the source URL context. Joining only on content_id can mix links from different observations of identical HTML.</AlertDescription></Alert><p>For a parent element, match both <code>content_id</code> and <code>child.parent_index = parent.element_index</code>. A subtree occupies element indices from <code>element_index</code> inclusive to <code>subtree_end_index</code> exclusive.</p><HtmlStructureIllustration /><p>HTML parsing normalizes the captured document. Elements preserve tags, attributes, hierarchy, document order, direct text, and trailing text; the projection is not a byte-for-byte reconstruction. Other content formats can have a content object without HTML element rows.</p><TextPlacementIllustration /><p>The public interface exposes structural projections and source metadata, without a raw-file download or historical browser replay. Source URLs open the live site, which may have changed.</p></CardContent></Card></section>
    <section id="recipe" aria-labelledby="recipe-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="recipe-heading">Extract book listings</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>A book title and a price appear as <code>h1</code> and <code>p.price_color</code> elements. In Periplus, you can query those elements as rows in the same table. This query pairs a title with a price under the same parent, keeping recommendation prices elsewhere on the page out of that pairing.</p><ol className="flex list-decimal flex-col gap-5 pl-5"><li><strong>Choose the pages and their observation.</strong><p>Filter to Books to Scrape product URLs. Keep one observation per requested URL using the latest recorded date, with an ID tie-breaker. Select at most 20 URLs before joining their elements. Undated observations sort last; their actual collection order is unknown.</p></li><li><strong>Define your fields from structure.</strong><p>Join on <code>content_id</code> to reach the HTML. Match a heading and a price with the same <code>parent_index</code>, filter the price by its class attribute, and parse the amount into a decimal column.</p></li><li><strong>Keep the context with the data.</strong><p>Return the source URL and collection date beside the title and price. The source is a practice website: this demonstrates product extraction, not a live market dataset.</p></li></ol><Example title="Book titles, prices, and source URLs" description={featuredDataset.scope} sql={featuredDataset.sql} /><h3 className="font-medium">Adjust extraction scope</h3><p>Change the selected fields or filters to suit your analysis. Expanding the URL sample changes which pages are eligible; increasing the final LIMIT only changes how many matching rows can be returned. An output limit does not limit the number of input rows scanned.</p><p>Structure gives you extraction control, not a universal product schema. Site-specific rules can need changes when page layouts change. Nested text also matters: <code>text_direct</code> excludes child-element text, as the text-placement illustration above explains.</p></CardContent></Card></section>
    <section id="examples" aria-labelledby="examples-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="examples-heading">SQL patterns</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><Example title="Extract headings and attributes" description="Select ten observations before expanding their HTML. Direct text excludes descendant text; an h1 may contain additional text in child elements. Non-HTML content has no HTML element rows." sql={headings} /><Example title="Explore outgoing links" description="Link occurrences preserve repeated anchors. A destination appearing multiple times is not automatically a duplicate error." sql={links} /><Example title="Choose one observation per URL" description="Chooses the latest dated observation, with a stable ID tie-breaker. It does not imply current live coverage; undated observations sort last. To choose the latest retained content instead, add WHERE content_id IS NOT NULL before QUALIFY." sql={latest} /></CardContent></Card></section>
    <section id="schema" aria-labelledby="schema-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="schema-heading">Public schema</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>These are public views. Their keys describe logical identity; they are not declarations of database-enforced primary keys on the views. Use DESCRIBE to inspect deployed column types and nullability.</p>{schemaReference.map(relation => <Card key={relation.name} id={relation.name.replaceAll('.', '-')}><CardHeader><CardTitle><h3 className="break-all"><code>{relation.name}</code></h3></CardTitle><CardDescription>{relation.grain}</CardDescription><CardDescription>Logical key: <code>{relation.key}</code></CardDescription></CardHeader><CardContent className="flex min-w-0 flex-col gap-4"><Table><TableHeader><TableRow><TableHead>Column / type</TableHead><TableHead>Meaning</TableHead></TableRow></TableHeader><TableBody>{relation.columns.map(([name, type, meaning]) => <TableRow key={name}><TableCell className="align-top whitespace-normal"><code className="break-all">{name}</code><CardDescription>{type}</CardDescription></TableCell><TableCell className="whitespace-normal">{meaning}</TableCell></TableRow>)}</TableBody></Table><Link className="story-link" href={sqlDraftLink(`DESCRIBE ${relation.name};`)}>Inspect deployed schema →</Link></CardContent></Card>)}</CardContent></Card></section>
    <section id="macros" aria-labelledby="macros-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="macros-heading">Functions and macros</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Use DuckDB SQL expressions and built-in functions such as <code>split_part</code>, <code>regexp_extract</code>, <code>try_cast</code>, and window functions. Access HTML attributes with <code>{"attributes['href']"}</code> or <code>{"attributes['class']"}</code>.</p><p>For nested text, the table macro <code>content.subtree_text(source_content_id, root_element_index)</code> assembles text in document order, excluding the root’s trailing text. It returns <code>text</code>, <code>truncated</code>, <code>total_chars</code>, and <code>element_count</code>. Optional <code>max_chars</code> defaults to 20,000 and <code>max_elements</code> to 10,000. A character limit truncates text; an oversized subtree raises an error, so select a smaller root.</p><p>There is no custom query extension to install. The public service restricts queries to the public catalogue and does not permit installing extensions, reading arbitrary files, or changing database state.</p></CardContent></Card></section>
    <section id="limits" aria-labelledby="limits-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="limits-heading">Query limits and behavior</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>The browser sends SQL to a read-only Python query service. Preparation validates and explains the query; execution independently prepares it and returns rows. SQL currently stays unchanged, with DuckDB optimizing the execution plan.</p><Table><TableHeader><TableRow><TableHead>Capability</TableHead><TableHead>Behavior</TableHead></TableRow></TableHeader><TableBody>{[["SQL", "One read-only statement over the public views. DESCRIBE, EXPLAIN, EXPLAIN ANALYZE, and SUMMARIZE use the same public scope checks."], ["Execution", "20-second interrupt deadline; 512 MB memory and 256 MB spill budget per query process."], ["Results", "Up to 1,000 rows and an 8 MiB result budget. Truncation is reported; CSV exports only the returned rows."], ["Busy service", "One operation per query process. Excess requests receive 429 with Retry-After; there is currently no queue."], ["Parameters", "Use ? placeholders and the SQL console’s JSON array of positional values."], ["Numbers", "Decimals and integers outside JavaScript’s safe range arrive as strings, alongside SQL type information."], ["Privacy", "SQL and parameters are logged. Shared query links include both. Do not include secrets."]].map(([name, value]) => <TableRow key={name}><TableCell className="align-top">{name}</TableCell><TableCell className="whitespace-normal">{value}</TableCell></TableRow>)}</TableBody></Table><p>A LIMIT bounds output, not necessarily work. Sorting, aggregation, and joins may still scan substantial data. Filter observations and select the columns you need before expanding HTML. EXPLAIN ANALYZE executes the query and consumes its execution budget.</p><p>Missing content can reflect failure, an empty response, or a decision not to retain it. HTML projections may become available after collection finishes. Observation times describe captured data, not a guarantee of freshness; live website links can show different content.</p></CardContent></Card></section>
    </div>
    </div>
  </main>
}
