import type { Metadata } from "next"
import { pageMetadata } from "@/lib/seo"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { buttonVariants } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { HtmlStructureIllustration } from "@/components/illustrations/html-structure"
import { featuredDataset } from "@/lib/datasets"
import { SqlExample } from "@/components/sql-example"
import { schemaReference } from "@/lib/schema-reference"

export const metadata: Metadata = pageMetadata("/docs", "Documentation", "Use Periplus core through the DuckDB catalogue and query service. Collection, schema, joins, extraction patterns, and execution semantics.")

const collectionCaptures = `SELECT *
FROM public_v1.capture
WHERE list_contains(request_ids, CAST(? AS UUID));`

const quickStart = `SELECT requested_url, captured_at, http_status_code, content_id
FROM public_v1.capture
ORDER BY captured_at DESC NULLS LAST, capture_id
LIMIT 20;`
const headings = `WITH pages AS (
  SELECT capture_id, requested_url, content_id
  FROM public_v1.capture
  WHERE content_id IS NOT NULL
  ORDER BY captured_at DESC NULLS LAST, capture_id
  LIMIT 10
)
SELECT p.requested_url, h.node_index,
       h.text_direct AS heading, h.attributes['class'] AS css_class
FROM pages p
JOIN public_v1.html_element h USING (content_id)
WHERE h.tag = 'h1'
ORDER BY p.capture_id, h.node_index
LIMIT 100;`
const links = `WITH pages AS (
  SELECT capture_id, effective_url
  FROM public_v1.capture
  WHERE content_id IS NOT NULL
  ORDER BY captured_at DESC NULLS LAST, capture_id
  LIMIT 10
)
SELECT p.effective_url AS source_url, l.resolved_url
FROM pages p
JOIN public_v1.link_occurrence l USING (capture_id)
ORDER BY p.effective_url, l.node_index
LIMIT 100;`
const latest = `SELECT requested_url, captured_at, http_status_code, content_id
FROM public_v1.capture
QUALIFY row_number() OVER (
  PARTITION BY requested_url
  ORDER BY captured_at DESC NULLS LAST, capture_id DESC
) = 1
ORDER BY requested_url
LIMIT 20;`

function Example({ title, description, sql }: { title: string; description: string; sql: string }) {
  return <Card className="docs-example"><CardHeader><CardTitle><h3 className="font-medium">{title}</h3></CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="flex min-w-0 flex-col gap-4"><SqlExample sql={sql} /></CardContent></Card>
}

export default function Page() {
  return <main className="docs-page mx-auto max-w-7xl px-5 pb-12 sm:px-8">
    <header className="flex flex-wrap items-baseline justify-between gap-2 py-6"><h1 className="text-xl font-medium">Documentation</h1><p className="text-sm text-muted-foreground">Collect pages, query the catalogue, and extract structured data.</p></header>
    <div className="grid items-start gap-8 lg:grid-cols-[220px_minmax(0,1fr)]">
    <aside className="lg:sticky lg:top-6 lg:max-h-[calc(100vh-3rem)] lg:overflow-y-auto">
      <nav aria-label="Documentation sections" className="flex flex-col gap-5">
        {[
          { title: "Get started", links: [["quick-start", "Run your first query"], ["how-it-works", "Collection and coverage"], ["building", "Collection requests"]] },
          { title: "Guides", links: [["joins", "Identity and joins"], ["recipe", "Extract book listings"], ["examples", "SQL patterns"]] },
          { title: "Reference", links: [["schema", "Public schema"], ["macros", "Functions and macros"], ["limits", "Query limits and behavior"]] },
          { title: "SDK", links: [["sdk", "Python SDK"]] },
        ].map(group => <div key={group.title} className="flex flex-col gap-1"><CardDescription className="px-3"><strong>{group.title}</strong></CardDescription>{group.links.map(([id, label]) => <Link key={id} href={`#${id}`} className={buttonVariants({ variant: "ghost", size: "sm" }) + " justify-start whitespace-normal h-auto py-2"}>{label}</Link>)}</div>)}
      </nav>
    </aside>
    <div className="flex min-w-0 flex-col gap-8">

    <section id="quick-start" aria-labelledby="quick-start-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="quick-start-heading">Run your first query</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Periplus exposes a DuckLake catalogue through standard DuckDB SQL. Run queries against the configured catalogue or through the query service. Each row in <code>capture</code> has retained content. The same URL can appear more than once, and retained HTTP error responses are included.</p><Example title="Recent captures" description="Up to 20 captures, with dated captures first. Acquisitions without retained content are excluded." sql={quickStart} /><p>The query API defaults to <code>public_v1</code>: use <code>capture</code> or <code>public_v1.capture</code>. Requests may specify <code>schema_version: &quot;public_v1&quot;</code>; unsupported versions are rejected. Responses report the resolved schema version separately from the data snapshot.</p></CardContent></Card></section>
    <section id="how-it-works" aria-labelledby="how-it-works-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="how-it-works-heading">Collection and coverage</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Periplus observes a page in a browser after configured loading and interaction steps. That document records one observed state of a page, rather than every possible interactive or personalised state.</p><p>Periplus retains observed content immutably and shares identical byte sequences through content identities. It records captures, then builds HTML and link projections separately. Collection can finish before those projections are queryable.</p><p>Coverage includes selected sources. It offers neither a representative sample of the web nor a uniform refresh schedule. Collection dates can be missing; the latest date for a site does not establish that all its pages are fresh.</p><p>Submit collection intent through the control API. A link found in a page does not mean its destination has been collected. Check available captures and projections before relying on a source in your dataset.</p></CardContent></Card></section>
    <section id="building" aria-labelledby="building-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="building-heading">Collection requests</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>A collection defines a bounded request for pages. Submit URL seeds through the control API with explicit depth and page limits.</p><p>A page limit means “up to N”. Collections can share acquisitions while retaining their own selection and accounting. Seed SQL selects from the corpus; follow SQL selects from the current page’s navigation and cannot join history.</p><Alert><AlertDescription>Collection settlement and catalogue readiness are separate. After a collection finishes, verify the captures and applicable projections before running extraction queries.</AlertDescription></Alert><h3 className="font-medium">Select captures for a coverage request</h3><p>Bind the coverage request UUID as the positional parameter. Each capture appears once, with a sorted, unique list of request IDs including shared and reused results. Membership can arrive after the capture; an empty list does not imply that no request exists.</p><Example title="Request captures" description="Filter request_ids to find the captures supplied to your coverage request." sql={collectionCaptures} /><h3 className="font-medium">Reproducibility</h3><p>SQL preserves the extraction method. Identical results also require the same input data, schema, and deterministic semantics. A source snapshot reference records the input version; it does not pin a future rerun.</p></CardContent></Card></section>


    <section id="joins" aria-labelledby="joins-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="joins-heading">Identity and joins</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Two URLs—or two visits to the same URL—can retain identical bytes. Those captures share a <code>content_id</code>. HTML structure is stored once for that content; joining it to captures repeats it for each matching capture.</p><Table tabIndex={0} aria-label="Identity and join keys"><TableHeader><TableRow><TableHead>From → to</TableHead><TableHead>Join on</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Capture → content object</TableCell><TableCell><code>content_id</code></TableCell></TableRow><TableRow><TableCell>Capture → HTML elements</TableCell><TableCell><code>content_id</code></TableCell></TableRow><TableRow><TableCell>Capture → link occurrences</TableCell><TableCell><code>capture_id</code></TableCell></TableRow><TableRow><TableCell>Link occurrence → capture → HTML element</TableCell><TableCell><code>content_id + node_index</code></TableCell></TableRow></TableBody></Table><p>Use a LEFT JOIN to retain captures without matching HTML structure. An INNER JOIN keeps only matches. Counting joined HTML rows counts elements, not pages; choose distinct URLs, capture IDs, or content IDs according to your question.</p><Alert><AlertDescription>Link resolution belongs to a capture. Join links on capture_id to preserve the source URL context. Joining only on content_id can mix links from different captures of identical HTML.</AlertDescription></Alert><p>For a parent element, match both <code>content_id</code> and <code>child.parent_index = parent.node_index</code>. A subtree occupies node indices from <code>node_index</code> inclusive to <code>subtree_end_index</code> exclusive.</p><HtmlStructureIllustration /><p>HTML parsing normalizes the captured document. Elements preserve tags, attributes, hierarchy and direct text. The <code>html_node</code> relation also exposes text nodes, comments and the document root. Nodes and elements share depth-first positions; sibling positions count every node type. Node references belong to the returned catalogue snapshot. Parsed structure is not a byte-for-byte reconstruction. Other content formats can have a content object without HTML element rows.</p><p>Retrieve original captured bytes with <code>GET /api/content/&#123;content_id&#125;</code>. The download preserves the bytes identified by the SHA-256 content ID. The catalogue exposes structural projections and source metadata. A source URL identifies the live site; its current content may differ from the retained capture.</p></CardContent></Card></section>
    <section id="recipe" aria-labelledby="recipe-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="recipe-heading">Extract book listings</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>A book title and a price appear as <code>h1</code> and <code>p.price_color</code> elements. In Periplus, you can query those elements as rows in the same table. This query pairs a title with a price under the same parent, keeping recommendation prices elsewhere on the page out of that pairing.</p><ol className="flex list-decimal flex-col gap-5 pl-5"><li><strong>Choose the pages and their capture.</strong><p>Filter to Books to Scrape product URLs. Keep one capture per requested URL using the latest recorded date, with an ID tie-breaker. Select at most 20 URLs before joining their elements. Undated captures sort last; their actual collection order is unknown.</p></li><li><strong>Define your fields from structure.</strong><p>Join on <code>content_id</code> to reach the HTML. Match a heading and a price with the same <code>parent_index</code>, filter the price by its class attribute, and parse the amount into a decimal column.</p></li><li><strong>Keep the context with the data.</strong><p>Return the source URL and collection date beside the title and price. The source is a practice website: this demonstrates product extraction, not a live market dataset.</p></li></ol><Example title="Book titles, prices, and source URLs" description={featuredDataset.scope} sql={featuredDataset.sql} /><h3 className="font-medium">Adjust extraction scope</h3><p>Change the selected fields or filters to suit your analysis. Expanding the URL sample changes which pages are eligible; increasing the final LIMIT only changes how many matching rows can be returned. An output limit does not limit the number of input rows scanned.</p><p>Structure gives you extraction control, not a universal product schema. Site-specific rules can need changes when page layouts change. Nested text also matters: <code>text_direct</code> excludes child-element text. Use <code>subtree_text</code> when your field includes nested elements.</p></CardContent></Card></section>
    <section id="examples" aria-labelledby="examples-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="examples-heading">SQL patterns</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><Example title="Extract headings and attributes" description="Select ten captures before expanding their HTML. Direct text excludes descendant text; an h1 may contain additional text in child elements. Non-HTML content has no HTML element rows." sql={headings} /><Example title="Explore outgoing links" description="Link occurrences preserve repeated anchors. A destination appearing multiple times is not automatically a duplicate error." sql={links} /><Example title="Choose one capture per URL" description="Chooses the latest dated capture, with a stable ID tie-breaker. It does not imply current live coverage; undated captures sort last. Every capture already has retained content." sql={latest} /></CardContent></Card></section>
    <section id="schema" aria-labelledby="schema-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="schema-heading">Public schema</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>These are public views. Their keys describe logical identity; they are not declarations of database-enforced primary keys on the views. Use DESCRIBE to inspect deployed column types and nullability.</p>{schemaReference.map(relation => <Card key={relation.name} id={relation.name.replaceAll('.', '-')}><CardHeader><CardTitle><h3 className="break-all"><code>{relation.name}</code></h3></CardTitle><CardDescription>{relation.grain}</CardDescription><CardDescription>Logical key: <code>{relation.key}</code></CardDescription></CardHeader><CardContent className="flex min-w-0 flex-col gap-4"><Table aria-label={`${relation.name} columns`}><TableHeader><TableRow><TableHead>Column / type</TableHead><TableHead>Meaning</TableHead></TableRow></TableHeader><TableBody>{relation.columns.map(([name, type, meaning]) => <TableRow key={name}><TableCell className="align-top whitespace-normal"><code className="break-all">{name}</code><CardDescription>{type}</CardDescription></TableCell><TableCell className="whitespace-normal">{meaning}</TableCell></TableRow>)}</TableBody></Table><code>{`DESCRIBE ${relation.name};`}</code></CardContent></Card>)}</CardContent></Card></section>
    <section id="macros" aria-labelledby="macros-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="macros-heading">Functions and macros</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Use DuckDB SQL expressions and built-in functions such as <code>split_part</code>, <code>regexp_extract</code>, <code>try_cast</code>, and window functions. Access HTML attributes with <code>{"attributes['href']"}</code> or <code>{"attributes['class']"}</code>.</p><p>For nested text, the table macro <code>public_v1.subtree_text(source_content_id, root_node_index)</code> assembles text in document order, including only text nodes within the selected subtree, excluding comments. It returns <code>text</code>, <code>truncated</code>, <code>total_chars</code>, and <code>node_count</code>. Optional <code>max_chars</code> defaults to 20,000 and <code>max_nodes</code> to 10,000. A character limit truncates text; an oversized subtree raises an error, so select a smaller root.</p><p>There is no custom query extension to install. The public service restricts queries to the public catalogue and does not permit installing extensions, reading arbitrary files, or changing database state.</p></CardContent></Card></section>
    <section id="limits" aria-labelledby="limits-heading" className="scroll-mt-6"><Card><CardHeader><CardTitle><h2 id="limits-heading">Query limits and behavior</h2></CardTitle></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>The query service accepts SQL and positional parameters through POST /query/prep and POST /query/exec. Preparation validates and explains the query; execution independently prepares it and returns rows. GET /query/helpers describes the installed helpers. SQL currently stays unchanged, with DuckDB optimizing the execution plan.</p><p>These limits apply to the query service. Direct DuckDB connections use their connection settings and do not inherit the service’s HTTP result caps.</p><Table aria-label="Query limits and behavior"><TableHeader><TableRow><TableHead>Capability</TableHead><TableHead>Behavior</TableHead></TableRow></TableHeader><TableBody>{[["SQL", "One read-only statement over the public views. DESCRIBE, EXPLAIN, EXPLAIN ANALYZE, and SUMMARIZE use the same public scope checks."], ["Execution", "Operator-configured interrupt deadline (20 seconds by default). Default memory and spill budgets are 512 MB and 256 MB per query process; deployment configuration can override them."], ["Results", "Operator-configured row and result-size limits (1,000 rows and 8 MiB by default). Truncation is reported explicitly; returned rows may be incomplete."], ["Busy service", "One operation per query process. Excess requests receive 429 with Retry-After; there is currently no queue."], ["Parameters", "Use ? placeholders and supply positional values in the request parameters array."], ["Numbers", "Decimals and integers outside JavaScript’s safe range arrive as strings, alongside SQL type information."]].map(([name, value]) => <TableRow key={name}><TableCell className="align-top">{name}</TableCell><TableCell className="whitespace-normal">{value}</TableCell></TableRow>)}</TableBody></Table><p>A LIMIT bounds output, not necessarily work. Sorting, aggregation, and joins may still scan substantial data. Filter captures and select the columns you need before expanding HTML. EXPLAIN ANALYZE executes the query and consumes its execution budget.</p><p>Acquisitions without retained content do not appear in capture. A capture with no matching HTML nodes may be non-HTML or still awaiting materialization; absence of projected rows is not proof of an empty document. HTML projections may become available after collection finishes. Capture times describe captured data, not a guarantee of freshness; live website links can show different content.</p></CardContent></Card></section>
    <section id="sdk" aria-labelledby="sdk-heading" className="scroll-mt-6"><Card><CardHeader><div className="flex items-center gap-3"><CardTitle><h2 id="sdk-heading">Python SDK</h2></CardTitle><Badge variant="secondary">public_v1</Badge></div><CardDescription>Read-only Python access through the same public query API as this workspace.</CardDescription></CardHeader><CardContent className="flex min-w-0 flex-col gap-5 text-sm leading-relaxed"><p>Use the SDK from the same Periplus source checkout as this deployment, with Python 3.11 or newer. These public_v1 examples require the updated source SDK; the previously published 0.2.0 release predates this contract. Configure your deployment’s public application URL; no service token or lake credentials are needed.</p><Card className="docs-code-box"><CardHeader><CardDescription>Terminal</CardDescription></CardHeader><CardContent><pre tabIndex={0} aria-label="Install Python SDK"><code>python -m pip install ./packages/periplus-python-sdk</code></pre></CardContent></Card><Card className="docs-code-box"><CardHeader><CardDescription>Python</CardDescription></CardHeader><CardContent><pre tabIndex={0} aria-label="Python SDK example"><code>{`from periplus_sdk import Client

with Client("https://your-periplus-host") as client:
    result = client.execute(
        "SELECT capture_id FROM public_v1.capture LIMIT ?", [10]
    )
    print(result.columns, result.rows)
    print(result.schema_version, result.source_snapshot, result.truncated)`}</code></pre></CardContent></Card><p><code>prepare(sql, parameters)</code> returns diagnostics and a plan. <code>execute(sql, parameters)</code> independently validates and runs the query. <code>helpers()</code> describes installed SQL helpers. Use <code>AsyncClient</code> with an async context manager and await these methods for asynchronous Python.</p><p>The same public access settings and query limits apply. Results preserve SQL types and explicit truncation; the SDK never retries or fetches more rows automatically. SQL and parameters are recorded as SDK operations in private, best-effort query history for 30 days; result rows are not stored.</p></CardContent></Card></section>
    </div>
    </div>
  </main>
}
