import {
  ArrowLeftIcon,
  BracesIcon,
  FileArchiveIcon,
  SaveIcon,
  ShieldAlertIcon,
  Trash2Icon,
} from "lucide-react"
import { useState, type ReactNode } from "react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import {
  useDataSchema,
  useDeleteDataSchema,
  useUpdateDataSchema,
} from "@/hooks/use-resource-data"
import type { DataSchemaDetailRecord } from "@/types/resources"

export function DataSchemaDetailPage({ schemaId }: { schemaId: string }) {
  const schemaQuery = useDataSchema(schemaId)
  const schema = schemaQuery.data

  if (schemaQuery.isLoading) {
    return <CenteredText>Loading data schema...</CenteredText>
  }

  if (!schema) {
    return (
      <div className="flex min-h-0 w-full flex-col gap-3">
        <BackButton />
        <div className="rounded-md border bg-card/80 p-4 text-sm text-muted-foreground">
          Data schema not found.
        </div>
      </div>
    )
  }

  return (
    <div className="flex min-h-0 w-full flex-col gap-4 overflow-y-auto">
      <section className="flex flex-wrap items-center justify-between gap-3 border-b pb-4">
        <div className="flex min-w-0 items-center gap-2">
          <BracesIcon className="size-4 text-muted-foreground" />
          <h1 className="truncate text-lg font-medium">Data Schema</h1>
          <Badge variant="outline">{schema.schema_type}</Badge>
          <Badge variant={schema.enabled ? "secondary" : "destructive"}>
            {schema.enabled ? "Enabled" : "Disabled"}
          </Badge>
        </div>
        <BackButton />
      </section>

      <section className="grid gap-3 lg:grid-cols-2">
        <DetailGroup
          title="Identity"
          items={[
            ["Schema ID", schema.id],
            ["Identity Key", schema.identity_key],
            ["Match", schema.match],
            ["Priority", String(schema.priority)],
            ["Schema Hash", schema.schema_hash],
            ["Prompt Hash", schema.prompt_hash],
            ["Target Hash", schema.target_json_hash],
          ]}
        />
        <DetailGroup
          title="Scope"
          items={[
            ["Domain", schema.domain],
            ["Path", schema.path],
            ["Validation", schema.validation_status],
            ["Created", formatDate(schema.created_at)],
            ["Updated", formatDate(schema.updated_at)],
            ["Task Runs", String(schema.task_run_count)],
            ["Warnings", String(schema.warning_count)],
          ]}
        />
        <DetailGroup
          title="Provenance"
          items={[
            ["Generated By Run", schema.generated_by_task_run_id],
            ["Generated From Crawl", schema.generated_from_crawl_id],
            ["Generated From Artifact", schema.generated_from_artifact_id],
          ]}
        />
        <DetailGroup
          title="Failure State"
          items={[
            ["Failure Count", String(schema.failure_count)],
            ["Last Failed At", formatDate(schema.last_failed_at)],
            ["Last Error", schema.last_error],
          ]}
        />
      </section>

      <section className="rounded-md border bg-card/80 p-3">
        <h2 className="mb-2 text-sm font-medium">Prompt</h2>
        <p className="text-sm leading-6 whitespace-pre-wrap text-muted-foreground">
          {schema.prompt}
        </p>
      </section>

      <SchemaAdminEditor key={schema.id} schema={schema} />

      <LinkActions schema={schema} />

      <WarningDetails schema={schema} />

      <section className="grid gap-3 xl:grid-cols-2">
        <JsonPanel title="Schema JSON" value={schema.schema_json} />
        <JsonPanel title="Inputs" value={schema.inputs_json} />
        <JsonPanel
          title="Warning Metadata"
          value={schema.warnings_json}
          compact
        />
      </section>
    </div>
  )
}

function SchemaAdminEditor({ schema }: { schema: DataSchemaDetailRecord }) {
  const updateSchema = useUpdateDataSchema(schema.id)
  const deleteSchema = useDeleteDataSchema(schema.id)
  const [match, setMatch] = useState(schema.match)
  const [enabled, setEnabled] = useState(schema.enabled)
  const [priority, setPriority] = useState(String(schema.priority))
  const [validationStatus, setValidationStatus] = useState(
    schema.validation_status ?? ""
  )
  const [schemaJson, setSchemaJson] = useState(
    JSON.stringify(schema.schema_json, null, 2)
  )

  const save = () => {
    let parsedSchema: Record<string, unknown>
    try {
      const parsed = JSON.parse(schemaJson) as unknown
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        toast.error("Schema JSON must be an object.")
        return
      }
      parsedSchema = parsed as Record<string, unknown>
    } catch {
      toast.error("Schema JSON is invalid.")
      return
    }

    const parsedPriority = Number(priority)
    if (!Number.isInteger(parsedPriority)) {
      toast.error("Priority must be an integer.")
      return
    }

    updateSchema.mutate({
      match,
      enabled,
      priority: parsedPriority,
      validation_status: validationStatus.trim() || null,
      schema_json: parsedSchema,
    })
  }

  const deleteCurrentSchema = () => {
    if (
      !window.confirm(
        "Delete this data schema? Existing task runs will keep their output, but this schema will no longer be reusable."
      )
    ) {
      return
    }

    deleteSchema.mutate(undefined, {
      onSuccess: () => {
        window.history.pushState(null, "", "/cache/data-schemas")
        window.dispatchEvent(new PopStateEvent("popstate"))
      },
    })
  }

  return (
    <section className="rounded-md border bg-card/80 p-3">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-sm font-medium">Admin</h2>
        <div className="flex flex-wrap gap-2">
          <Button
            size="sm"
            variant="destructive"
            onClick={deleteCurrentSchema}
            disabled={deleteSchema.isPending}
          >
            <Trash2Icon />
            Delete
          </Button>
          <Button size="sm" onClick={save} disabled={updateSchema.isPending}>
            <SaveIcon />
            Save
          </Button>
        </div>
      </div>
      <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_8rem_10rem]">
        <Field label="Match">
          <Input
            value={match}
            onChange={(event) => setMatch(event.target.value)}
          />
        </Field>
        <Field label="Priority">
          <Input
            type="number"
            step={1}
            value={priority}
            onChange={(event) => setPriority(event.target.value)}
          />
        </Field>
        <Field label="Enabled">
          <div className="flex h-7 items-center gap-2">
            <Switch checked={enabled} onCheckedChange={setEnabled} />
            <span className="text-xs text-muted-foreground">
              {enabled ? "On" : "Off"}
            </span>
          </div>
        </Field>
      </div>
      <div className="mt-3 grid gap-3 xl:grid-cols-[18rem_minmax(0,1fr)]">
        <Field label="Validation">
          <Input
            value={validationStatus}
            onChange={(event) => setValidationStatus(event.target.value)}
          />
        </Field>
        <Field label="Schema JSON">
          <Textarea
            className="min-h-64 font-mono"
            value={schemaJson}
            onChange={(event) => setSchemaJson(event.target.value)}
          />
        </Field>
      </div>
    </section>
  )
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="grid gap-1">
      <Label>{label}</Label>
      {children}
    </div>
  )
}

function LinkActions({ schema }: { schema: DataSchemaDetailRecord }) {
  return (
    <section className="flex flex-wrap gap-2">
      {schema.generated_from_artifact_id ? (
        <Button
          variant="outline"
          size="sm"
          nativeButton={false}
          render={
            <a href={`/cache/artifacts/${schema.generated_from_artifact_id}`} />
          }
        >
          <FileArchiveIcon />
          Source Artifact
        </Button>
      ) : null}
    </section>
  )
}

function BackButton() {
  return (
    <Button
      variant="outline"
      size="sm"
      nativeButton={false}
      render={<a href="/cache/data-schemas" />}
    >
      <ArrowLeftIcon />
      Data Schemas
    </Button>
  )
}

function WarningDetails({ schema }: { schema: DataSchemaDetailRecord }) {
  const warnings = parseWarnings(schema.warnings_json.warnings)

  return (
    <section className="rounded-md border bg-card/80 p-3">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <ShieldAlertIcon className="size-4 text-muted-foreground" />
          <h2 className="text-sm font-medium">Warnings</h2>
        </div>
        <Badge variant={schema.warning_count > 0 ? "destructive" : "outline"}>
          {schema.warning_count} total
        </Badge>
      </div>
      {warnings.length > 0 ? (
        <div className="grid gap-3">
          {warnings.map((warning) => (
            <article
              key={warning.code}
              className="grid gap-3 rounded-md border bg-muted/30 p-3"
            >
              <div className="min-w-0">
                <div className="truncate text-sm font-medium">
                  {warning.name}
                </div>
                <div className="truncate font-mono text-xs text-muted-foreground">
                  {warning.code}
                </div>
              </div>
              {warning.description ? (
                <p className="text-xs leading-5 text-muted-foreground">
                  {warning.description}
                </p>
              ) : null}
            </article>
          ))}
        </div>
      ) : (
        <div className="text-xs text-muted-foreground">No warning details.</div>
      )}
    </section>
  )
}

function DetailGroup({
  title,
  items,
}: {
  title: string
  items: Array<[string, string | null]>
}) {
  return (
    <section className="rounded-md border bg-card/80 p-3">
      <h2 className="mb-2 text-sm font-medium">{title}</h2>
      <dl className="grid gap-2 text-xs">
        {items.map(([label, value]) => (
          <div
            key={label}
            className="grid gap-1 md:grid-cols-[9rem_minmax(0,1fr)]"
          >
            <dt className="text-muted-foreground">{label}</dt>
            <dd className="min-w-0 font-mono break-words">{value || "-"}</dd>
          </div>
        ))}
      </dl>
    </section>
  )
}

function JsonPanel({
  title,
  value,
  compact = false,
}: {
  title: string
  value: unknown
  compact?: boolean
}) {
  return (
    <section className="min-w-0 rounded-md border bg-card/80 p-3">
      <h2 className="mb-2 text-sm font-medium">{title}</h2>
      <pre
        className={
          compact
            ? "max-h-64 overflow-auto rounded-md bg-muted/40 p-3 text-xs"
            : "max-h-[34rem] overflow-auto rounded-md bg-muted/40 p-3 text-xs"
        }
      >
        {JSON.stringify(value, null, 2)}
      </pre>
    </section>
  )
}

function CenteredText({ children }: { children: string }) {
  return (
    <div className="flex min-h-0 w-full items-center justify-center text-sm text-muted-foreground">
      {children}
    </div>
  )
}

type SchemaWarning = {
  code: string
  name: string
  description: string | null
}

function parseWarnings(value: unknown): SchemaWarning[] {
  if (!Array.isArray(value)) {
    return []
  }

  return value.flatMap((item) => {
    if (!item || typeof item !== "object") {
      return []
    }
    const warning = item as Record<string, unknown>
    return [
      {
        code: String(warning.code ?? ""),
        name: String(warning.name ?? ""),
        description:
          typeof warning.description === "string" ? warning.description : null,
      },
    ]
  })
}

function formatDate(value: string | null) {
  if (!value) {
    return "-"
  }
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value))
}
