direction: right

style.fill: "#171c1e"

classes: {
  table: {
    style: {
      fill: "#273033"
      stroke: "#1c2224"
      font-color: "#f7fafa"
    }
  }
}

crawls: {
  shape: sql_table
  class: table
  crawl_id: UUID {
    constraint: primary_key
  }
  document_id: VARCHAR? {
    constraint: foreign_key
  }
  artifact_id: VARCHAR? {
    constraint: foreign_key
  }
}

documents: {
  shape: sql_table
  class: table
  document_id: VARCHAR {
    constraint: primary_key
  }
}

elements: {
  shape: sql_table
  class: table
  document_id: VARCHAR {
    constraint: foreign_key
  }
  element_index: INTEGER {
    constraint: primary_key
  }
}

artifacts: {
  shape: sql_table
  class: table
  artifact_id: VARCHAR {
    constraint: primary_key
  }
}

crawls.document_id -> documents.document_id: N : 1 {
  style.stroke: "#36b7df"
  style.font-color: "#9aa6aa"
}
documents.document_id -> elements.document_id: 1 : N {
  style.stroke: "#36b7df"
  style.font-color: "#9aa6aa"
}
crawls.artifact_id -> artifacts.artifact_id: N : 1 {
  style.stroke: "#36b7df"
  style.font-color: "#9aa6aa"
}
