"""baseline

Revision ID: 20260712_0001
Revises: 
Create Date: 2026-07-12 15:13:39.705774

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260712_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalogue_queries_archived_at', 'catalogue_queries', ['archived_at'], unique=False)
    op.create_table('catalogue_query_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('sql_hash', sa.Text(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['catalogue_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'id', name='uq_catalogue_query_revision_identity'),
    sa.UniqueConstraint('query_id', 'revision', name='uq_catalogue_query_revision_number')
    )
    op.create_index('ix_catalogue_query_revisions_query_id', 'catalogue_query_revisions', ['query_id'], unique=False)
    op.create_foreign_key(
        'fk_catalogue_queries_current_revision',
        'catalogue_queries',
        'catalogue_query_revisions',
        ['current_revision_id'],
        ['id'],
    )
    op.create_table('crawl_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_slug', sa.Text(), nullable=False),
    sa.Column('domain_group', sa.Text(), nullable=False),
    sa.Column('url_match_id', sa.UUID(), nullable=True),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_slug')
    )
    op.create_index('ix_crawl_policies_enabled', 'crawl_policies', ['enabled'], unique=False)
    op.create_index('ix_crawl_policies_match', 'crawl_policies', ['match'], unique=False)
    op.create_index('ix_crawl_policies_url_match_id', 'crawl_policies', ['url_match_id'], unique=False)
    op.create_table('data_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('schema_type', sa.Text(), nullable=False),
    sa.Column('target_json_hash', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.Text(), nullable=False),
    sa.Column('generated_from_crawl_id', sa.UUID(), nullable=True),
    sa.Column('generated_from_document_id', sa.Text(), nullable=True),
    sa.Column('generated_by_task_run_id', sa.UUID(), nullable=True),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_data_schemas_domain', 'data_schemas', ['domain'], unique=False)
    op.create_index('ix_data_schemas_enabled', 'data_schemas', ['enabled'], unique=False)
    op.create_index('ix_data_schemas_match', 'data_schemas', ['match'], unique=False)
    op.create_index('ix_data_schemas_prompt_hash', 'data_schemas', ['prompt_hash'], unique=False)
    op.create_index('ix_data_schemas_schema_type', 'data_schemas', ['schema_type'], unique=False)
    op.create_table('query_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('url_match_id', sa.UUID(), nullable=True),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('schema_type', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.Text(), nullable=False),
    sa.Column('generated_from_crawl_id', sa.UUID(), nullable=True),
    sa.Column('generated_from_document_id', sa.Text(), nullable=True),
    sa.Column('generated_by_task_run_id', sa.UUID(), nullable=True),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_query_schemas_domain', 'query_schemas', ['domain'], unique=False)
    op.create_index('ix_query_schemas_enabled', 'query_schemas', ['enabled'], unique=False)
    op.create_index('ix_query_schemas_match', 'query_schemas', ['match'], unique=False)
    op.create_index('ix_query_schemas_schema_type', 'query_schemas', ['schema_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('primitive', sa.Text(), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('schedule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identity_key', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_index('ix_tasks_archived_at', 'tasks', ['archived_at'], unique=False)
    op.create_index('ix_tasks_next_run_at', 'tasks', ['next_run_at'], unique=False)
    op.create_index('ix_tasks_primitive', 'tasks', ['primitive'], unique=False)
    op.create_table('url_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('path_pattern', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Text(), nullable=False),
    sa.Column('query_policy', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by_task_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_task_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'host', 'path_pattern', 'match_type', 'query_policy', name='uq_url_matches_identity')
    )
    op.create_index('ix_url_matches_domain', 'url_matches', ['domain'], unique=False)
    op.create_index('ix_url_matches_enabled', 'url_matches', ['enabled'], unique=False)
    op.create_index('ix_url_matches_host', 'url_matches', ['host'], unique=False)
    op.create_index('ix_url_matches_path_pattern', 'url_matches', ['path_pattern'], unique=False)
    op.create_foreign_key(
        'fk_crawl_policies_url_match',
        'crawl_policies',
        'url_matches',
        ['url_match_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_query_schemas_url_match',
        'query_schemas',
        'url_matches',
        ['url_match_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('catalogue_view_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ducklake_view_uuid', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=False),
    sa.Column('view_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_from_query_revision_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_from_query_revision_id'], ['catalogue_query_revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ducklake_view_uuid'),
    sa.UniqueConstraint('schema_name', 'view_name', name='uq_catalogue_view_reference_name')
    )
    op.create_index('ix_catalogue_view_references_archived_at', 'catalogue_view_references', ['archived_at'], unique=False)
    op.create_table('catalogue_materializations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('active_query_revision_id', sa.UUID(), nullable=True),
    sa.Column('view_reference_id', sa.UUID(), nullable=True),
    sa.Column('bound_ducklake_view_uuid', sa.UUID(), nullable=True),
    sa.Column('source_state', sa.Text(), nullable=False),
    sa.Column('definition_revision_id', sa.UUID(), nullable=False),
    sa.Column('refresh_mode', sa.Text(), nullable=False),
    sa.Column('scope_kind', sa.Text(), nullable=True),
    sa.Column('scope_column', sa.Text(), nullable=True),
    sa.Column('activation_snapshot', sa.BigInteger(), nullable=True),
    sa.Column('live_enabled', sa.Boolean(), nullable=False),
    sa.Column('backfill_enabled', sa.Boolean(), nullable=False),
    sa.Column('backfill_scopes_per_minute', sa.Integer(), nullable=False),
    sa.Column('partition_column', sa.Text(), nullable=True),
    sa.Column('ducklake_table_uuid', sa.UUID(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dematerialization_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(refresh_mode = 'full' AND scope_kind IS NULL AND scope_column IS NULL AND activation_snapshot IS NULL AND NOT live_enabled AND NOT backfill_enabled) OR (refresh_mode = 'scope_incremental' AND scope_kind = 'document' AND scope_column IS NOT NULL AND activation_snapshot IS NOT NULL)", name='ck_catalogue_materializations_mode_state'),
    sa.CheckConstraint("refresh_mode IN ('full', 'scope_incremental')", name='ck_catalogue_materializations_refresh_mode'),
    sa.CheckConstraint("scope_kind IS NULL OR scope_kind = 'document'", name='ck_catalogue_materializations_document_scope'),
    sa.CheckConstraint("source_state IN ('current', 'source_changing', 'source_changed')", name='ck_catalogue_materializations_source_state'),
    sa.CheckConstraint('(query_id IS NOT NULL AND active_query_revision_id IS NOT NULL AND view_reference_id IS NULL AND bound_ducklake_view_uuid IS NULL) OR (query_id IS NULL AND active_query_revision_id IS NULL AND view_reference_id IS NOT NULL AND bound_ducklake_view_uuid IS NOT NULL)', name='ck_catalogue_materializations_source_shape'),
    sa.CheckConstraint('(query_id IS NOT NULL) <> (view_reference_id IS NOT NULL)', name='ck_catalogue_materializations_one_source'),
    sa.CheckConstraint('backfill_scopes_per_minute > 0', name='ck_catalogue_materializations_positive_backfill_rate'),
    sa.ForeignKeyConstraint(['query_id', 'active_query_revision_id'], ['catalogue_query_revisions.query_id', 'catalogue_query_revisions.id'], name='fk_catalogue_materializations_active_query_revision'),
    sa.ForeignKeyConstraint(['query_id'], ['catalogue_queries.id'], ),
    sa.ForeignKeyConstraint(['view_reference_id'], ['catalogue_view_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalogue_materializations_archived_at', 'catalogue_materializations', ['archived_at'], unique=False)
    op.create_index('uq_catalogue_materializations_active_name', 'catalogue_materializations', ['name'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('uq_catalogue_materializations_active_query', 'catalogue_materializations', ['query_id'], unique=True, postgresql_where=sa.text('query_id IS NOT NULL AND archived_at IS NULL'))
    op.create_index('uq_catalogue_materializations_active_view', 'catalogue_materializations', ['view_reference_id'], unique=True, postgresql_where=sa.text('view_reference_id IS NOT NULL AND archived_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_catalogue_materializations_active_view', table_name='catalogue_materializations', postgresql_where=sa.text('view_reference_id IS NOT NULL AND archived_at IS NULL'))
    op.drop_index('uq_catalogue_materializations_active_query', table_name='catalogue_materializations', postgresql_where=sa.text('query_id IS NOT NULL AND archived_at IS NULL'))
    op.drop_index('uq_catalogue_materializations_active_name', table_name='catalogue_materializations', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_catalogue_materializations_archived_at', table_name='catalogue_materializations')
    op.drop_table('catalogue_materializations')
    op.drop_index('ix_catalogue_view_references_archived_at', table_name='catalogue_view_references')
    op.drop_table('catalogue_view_references')
    op.drop_constraint('fk_query_schemas_url_match', 'query_schemas', type_='foreignkey')
    op.drop_constraint('fk_crawl_policies_url_match', 'crawl_policies', type_='foreignkey')
    op.drop_index('ix_url_matches_path_pattern', table_name='url_matches')
    op.drop_index('ix_url_matches_host', table_name='url_matches')
    op.drop_index('ix_url_matches_enabled', table_name='url_matches')
    op.drop_index('ix_url_matches_domain', table_name='url_matches')
    op.drop_table('url_matches')
    op.drop_index('ix_tasks_primitive', table_name='tasks')
    op.drop_index('ix_tasks_next_run_at', table_name='tasks')
    op.drop_index('ix_tasks_archived_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_query_schemas_schema_type', table_name='query_schemas')
    op.drop_index('ix_query_schemas_match', table_name='query_schemas')
    op.drop_index('ix_query_schemas_enabled', table_name='query_schemas')
    op.drop_index('ix_query_schemas_domain', table_name='query_schemas')
    op.drop_table('query_schemas')
    op.drop_index('ix_data_schemas_schema_type', table_name='data_schemas')
    op.drop_index('ix_data_schemas_prompt_hash', table_name='data_schemas')
    op.drop_index('ix_data_schemas_match', table_name='data_schemas')
    op.drop_index('ix_data_schemas_enabled', table_name='data_schemas')
    op.drop_index('ix_data_schemas_domain', table_name='data_schemas')
    op.drop_table('data_schemas')
    op.drop_index('ix_crawl_policies_url_match_id', table_name='crawl_policies')
    op.drop_index('ix_crawl_policies_match', table_name='crawl_policies')
    op.drop_index('ix_crawl_policies_enabled', table_name='crawl_policies')
    op.drop_table('crawl_policies')
    op.drop_constraint('fk_catalogue_queries_current_revision', 'catalogue_queries', type_='foreignkey')
    op.drop_index('ix_catalogue_query_revisions_query_id', table_name='catalogue_query_revisions')
    op.drop_table('catalogue_query_revisions')
    op.drop_index('ix_catalogue_queries_archived_at', table_name='catalogue_queries')
    op.drop_table('catalogue_queries')
    # ### end Alembic commands ###
