"""baseline

Revision ID: 20260712_0001
Revises: 
Create Date: 2026-07-12 15:13:39.705774

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260712_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_catalogue_queries_slug')
    )
    op.create_index('ix_catalogue_queries_archived_at', 'catalogue_queries', ['archived_at'], unique=False)
    op.create_table('catalogue_query_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('sql_hash', sa.Text(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['catalogue_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'id', name='uq_catalogue_query_revision_identity'),
    sa.UniqueConstraint('query_id', 'revision', name='uq_catalogue_query_revision_number')
    )
    op.create_index('ix_catalogue_query_revisions_query_id', 'catalogue_query_revisions', ['query_id'], unique=False)
    op.create_foreign_key(
        'fk_catalogue_queries_current_revision',
        'catalogue_queries',
        'catalogue_query_revisions',
        ['current_revision_id'],
        ['id'],
    )
    op.create_table('crawl_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_rank', sa.Integer(), nullable=False),
    sa.Column('trial_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_rank >= 0', name='ck_crawl_profiles_cost_rank'),
    sa.CheckConstraint("transport IN ('http', 'browser', 'firecrawl')", name='ck_crawl_profiles_transport'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('uq_crawl_profiles_trial_cost', 'crawl_profiles', ['cost_rank'], unique=True, postgresql_where=sa.text('trial_eligible'))
    op.create_table('crawl_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('path_prefix', sa.Text(), nullable=False),
    sa.Column('path_mode', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_concurrency >= 1', name='ck_crawl_policies_concurrency'),
    sa.CheckConstraint("path_mode IN ('exact', 'prefix')", name='ck_crawl_policies_path_mode'),
    sa.CheckConstraint("scheme IN ('*', 'http', 'https')", name='ck_crawl_policies_scheme'),
    sa.ForeignKeyConstraint(['profile_id'], ['crawl_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'host', 'path_prefix', 'path_mode', name='uq_crawl_policies_match'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_crawl_policies_enabled', 'crawl_policies', ['enabled'], unique=False)
    op.create_index('ix_crawl_policies_host', 'crawl_policies', ['host'], unique=False)
    op.create_table('crawl_graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crawl_graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['crawl_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'id', name='uq_crawl_graph_nodes_graph_identity'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_crawl_graph_nodes_graph_name')
    )
    op.create_index('ix_crawl_graph_nodes_graph_id', 'crawl_graph_nodes', ['graph_id'], unique=False)
    op.add_column('crawl_graphs', sa.Column('root_node_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_crawl_graphs_root_node',
        'crawl_graphs',
        'crawl_graph_nodes',
        ['root_node_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('crawl_graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['crawl_graphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id', 'source_node_id'], ['crawl_graph_nodes.graph_id', 'crawl_graph_nodes.id'], name='fk_crawl_graph_edges_source_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id', 'target_node_id'], ['crawl_graph_nodes.graph_id', 'crawl_graph_nodes.id'], name='fk_crawl_graph_edges_target_node', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_crawl_graph_edges_graph_name')
    )
    op.create_index('ix_crawl_graph_edges_graph_id', 'crawl_graph_edges', ['graph_id'], unique=False)
    op.create_index('ix_crawl_graph_edges_source_node_id', 'crawl_graph_edges', ['source_node_id'], unique=False)
    op.create_index('ix_crawl_graph_edges_target_node_id', 'crawl_graph_edges', ['target_node_id'], unique=False)
    op.create_table('catalogue_view_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ducklake_view_uuid', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=False),
    sa.Column('view_name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_from_query_revision_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_from_query_revision_id'], ['catalogue_query_revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ducklake_view_uuid'),
    sa.UniqueConstraint('schema_name', 'view_name', name='uq_catalogue_view_reference_name'),
    sa.UniqueConstraint('slug', name='uq_catalogue_view_reference_slug')
    )
    op.create_index('ix_catalogue_view_references_archived_at', 'catalogue_view_references', ['archived_at'], unique=False)
    op.create_table('catalogue_materializations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_sql', sa.Text(), nullable=False),
    sa.Column('view_reference_id', sa.UUID(), nullable=False),
    sa.Column('bound_ducklake_view_uuid', sa.UUID(), nullable=False),
    sa.Column('source_state', sa.Text(), nullable=False),
    sa.Column('definition_revision_id', sa.UUID(), nullable=False),
    sa.Column('scope_kind', sa.Text(), nullable=False),
    sa.Column('scope_column', sa.Text(), nullable=False),
    sa.Column('activation_snapshot', sa.BigInteger(), nullable=False),
    sa.Column('live_enabled', sa.Boolean(), nullable=False),
    sa.Column('backfill_enabled', sa.Boolean(), nullable=False),
    sa.Column('backfill_scopes_per_minute', sa.Integer(), nullable=False),
    sa.Column('partition_column', sa.Text(), nullable=True),
    sa.Column('ducklake_table_uuid', sa.UUID(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dematerialization_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope_kind IN ('document', 'crawl')", name='ck_catalogue_materializations_scope'),
    sa.CheckConstraint("scope_column <> ''", name='ck_catalogue_materializations_scope_column'),
    sa.CheckConstraint("source_state IN ('current', 'source_changed')", name='ck_catalogue_materializations_source_state'),
    sa.CheckConstraint('backfill_scopes_per_minute > 0', name='ck_catalogue_materializations_positive_backfill_rate'),
    sa.ForeignKeyConstraint(['view_reference_id'], ['catalogue_view_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalogue_materializations_archived_at', 'catalogue_materializations', ['archived_at'], unique=False)
    op.create_index('uq_catalogue_materializations_active_name', 'catalogue_materializations', ['name'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('uq_catalogue_materializations_active_view', 'catalogue_materializations', ['view_reference_id'], unique=True, postgresql_where=sa.text('view_reference_id IS NOT NULL AND archived_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_catalogue_materializations_active_view', table_name='catalogue_materializations', postgresql_where=sa.text('view_reference_id IS NOT NULL AND archived_at IS NULL'))
    op.drop_index('uq_catalogue_materializations_active_name', table_name='catalogue_materializations', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_catalogue_materializations_archived_at', table_name='catalogue_materializations')
    op.drop_table('catalogue_materializations')
    op.drop_index('ix_catalogue_view_references_archived_at', table_name='catalogue_view_references')
    op.drop_table('catalogue_view_references')
    op.drop_index('ix_crawl_graph_edges_target_node_id', table_name='crawl_graph_edges')
    op.drop_index('ix_crawl_graph_edges_source_node_id', table_name='crawl_graph_edges')
    op.drop_index('ix_crawl_graph_edges_graph_id', table_name='crawl_graph_edges')
    op.drop_table('crawl_graph_edges')
    op.drop_constraint('fk_crawl_graphs_root_node', 'crawl_graphs', type_='foreignkey')
    op.drop_index('ix_crawl_graph_nodes_graph_id', table_name='crawl_graph_nodes')
    op.drop_table('crawl_graph_nodes')
    op.drop_table('crawl_graphs')
    op.drop_index('ix_crawl_policies_host', table_name='crawl_policies')
    op.drop_index('ix_crawl_policies_enabled', table_name='crawl_policies')
    op.drop_table('crawl_policies')
    op.drop_index('uq_crawl_profiles_trial_cost', table_name='crawl_profiles', postgresql_where=sa.text('trial_eligible'))
    op.drop_table('crawl_profiles')
    op.drop_constraint('fk_catalogue_queries_current_revision', 'catalogue_queries', type_='foreignkey')
    op.drop_index('ix_catalogue_query_revisions_query_id', table_name='catalogue_query_revisions')
    op.drop_table('catalogue_query_revisions')
    op.drop_index('ix_catalogue_queries_archived_at', table_name='catalogue_queries')
    op.drop_table('catalogue_queries')
    # ### end Alembic commands ###
