"""greenfield control plane baseline

Revision ID: 20260726_0001
Revises: 
Create Date: 2026-07-26 18:34:05.575013

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260726_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_node_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('crawl_graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['crawl_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'id', name='uq_crawl_graph_nodes_graph_identity'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_crawl_graph_nodes_graph_name')
    )
    op.create_index(op.f('ix_crawl_graph_nodes_graph_id'), 'crawl_graph_nodes', ['graph_id'], unique=False)
    op.create_foreign_key(
        'fk_crawl_graphs_root_node',
        'crawl_graphs',
        'crawl_graph_nodes',
        ['id', 'root_node_id'],
        ['graph_id', 'id'],
        initially='DEFERRED',
        deferrable=True,
    )
    op.create_table('crawl_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('path_prefix', sa.Text(), nullable=False),
    sa.Column('path_mode', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("path_mode IN ('exact', 'prefix')", name='ck_crawl_policies_path_mode'),
    sa.CheckConstraint("scheme IN ('*', 'http', 'https')", name='ck_crawl_policies_scheme'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'host', 'path_prefix', 'path_mode', name='uq_crawl_policies_match'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_crawl_policies_enabled', 'crawl_policies', ['enabled'], unique=False)
    op.create_index('ix_crawl_policies_host', 'crawl_policies', ['host'], unique=False)
    op.create_table('domain_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('host_match', sa.Text(), nullable=False),
    sa.Column('maximum_concurrency', sa.Integer(), nullable=False),
    sa.Column('minimum_request_interval_seconds', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('maximum_concurrency >= 1', name='ck_domain_policies_concurrency'),
    sa.CheckConstraint('minimum_request_interval_seconds >= 0', name='ck_domain_policies_interval'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_match'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_domain_policies_enabled', 'domain_policies', ['enabled'], unique=False)
    op.create_table('graph_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('trigger_kind', sa.Text(), nullable=False),
    sa.Column('trigger_schedule_id', sa.UUID(), nullable=True),
    sa.Column('catalogue_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('catalogue_consistency', sa.Text(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trigger_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_crawls', sa.Integer(), nullable=False),
    sa.Column('crawl_limit_reached', sa.Boolean(), nullable=False),
    sa.Column('root_admission_cursor', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('pending_request_count', sa.Integer(), nullable=False),
    sa.Column('acquisition_pending_count', sa.Integer(), nullable=False),
    sa.Column('failed_request_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('failure_groups', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("catalogue_consistency = 'run_frozen'", name='ck_graph_runs_catalogue_consistency'),
    sa.CheckConstraint("status IN ('queued', 'running', 'paused', 'completed', 'completed_with_errors', 'failed', 'cancelled')", name='ck_graph_runs_status'),
    sa.CheckConstraint("trigger_kind IN ('manual', 'schedule')", name='ck_graph_runs_trigger_kind'),
    sa.CheckConstraint('generation >= 1', name='ck_graph_runs_generation'),
    sa.CheckConstraint('max_crawls >= 1', name='ck_graph_runs_max_crawls'),
    sa.CheckConstraint('request_count >= 0 AND pending_request_count >= 0 AND acquisition_pending_count >= 0 AND failed_request_count >= 0 AND error_count >= 0', name='ck_graph_runs_nonnegative_counts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_runs_active', 'graph_runs', ['status', 'not_before'], unique=False, postgresql_where=sa.text("status IN ('queued', 'running', 'paused')"))
    op.create_index(op.f('ix_graph_runs_deadline_at'), 'graph_runs', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_graph_runs_graph_id'), 'graph_runs', ['graph_id'], unique=False)
    op.create_index(op.f('ix_graph_runs_not_before'), 'graph_runs', ['not_before'], unique=False)
    op.create_index(op.f('ix_graph_runs_status'), 'graph_runs', ['status'], unique=False)
    op.create_index(op.f('ix_graph_runs_trigger_schedule_id'), 'graph_runs', ['trigger_schedule_id'], unique=False)
    op.create_table('crawl_graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('dedupe_mode', sa.Enum('graph', 'crawl', 'document', name='crawl_graph_edge_dedupe_mode'), server_default='graph', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['graph_id', 'source_node_id'], ['crawl_graph_nodes.graph_id', 'crawl_graph_nodes.id'], name='fk_crawl_graph_edges_source_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id', 'target_node_id'], ['crawl_graph_nodes.graph_id', 'crawl_graph_nodes.id'], name='fk_crawl_graph_edges_target_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_id'], ['crawl_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_crawl_graph_edges_graph_name')
    )
    op.create_index(op.f('ix_crawl_graph_edges_graph_id'), 'crawl_graph_edges', ['graph_id'], unique=False)
    op.create_index(op.f('ix_crawl_graph_edges_source_node_id'), 'crawl_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_crawl_graph_edges_target_node_id'), 'crawl_graph_edges', ['target_node_id'], unique=False)
    op.create_table('crawl_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.Text(), nullable=True),
    sa.Column('effective_policy_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_crawl_id', sa.UUID(), nullable=True),
    sa.Column('source_edge_id', sa.UUID(), nullable=True),
    sa.Column('parent_request_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('failure_stage', sa.Text(), nullable=True),
    sa.Column('processing_failure_count', sa.Integer(), nullable=False),
    sa.Column('acquisition_attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'crawling', 'awaiting_navigation', 'evaluating_edges', 'completed', 'failed', 'cancelled')", name='ck_crawl_requests_status'),
    sa.CheckConstraint('generation >= 1', name='ck_crawl_requests_generation'),
    sa.CheckConstraint('processing_failure_count >= 0', name='ck_crawl_requests_processing_failures'),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_request_id'], ['crawl_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_run_id', 'identity', name='uq_crawl_requests_identity')
    )
    op.create_index(op.f('ix_crawl_requests_graph_run_id'), 'crawl_requests', ['graph_run_id'], unique=False)
    op.create_index(op.f('ix_crawl_requests_node_id'), 'crawl_requests', ['node_id'], unique=False)
    op.create_index(op.f('ix_crawl_requests_not_before'), 'crawl_requests', ['not_before'], unique=False)
    op.create_index('ix_crawl_requests_run_node_status', 'crawl_requests', ['graph_run_id', 'node_id', 'status'], unique=False)
    op.create_index('ix_crawl_requests_runnable', 'crawl_requests', ['status', 'not_before', 'priority'], unique=False)
    op.create_index(op.f('ix_crawl_requests_source_edge_id'), 'crawl_requests', ['source_edge_id'], unique=False)
    op.create_index(op.f('ix_crawl_requests_status'), 'crawl_requests', ['status'], unique=False)
    op.create_table('crawl_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maximum_run_count', sa.Integer(), nullable=True),
    sa.Column('max_crawls', sa.Integer(), nullable=False),
    sa.Column('root_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overlap_policy', sa.Text(), nullable=False),
    sa.Column('misfire_policy', sa.Text(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.UUID(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("misfire_policy IN ('skip', 'run_once')", name='ck_crawl_schedules_misfire_policy'),
    sa.CheckConstraint("overlap_policy IN ('skip', 'allow')", name='ck_crawl_schedules_overlap_policy'),
    sa.CheckConstraint('max_crawls >= 1 AND max_crawls <= 1000000', name='ck_crawl_schedules_max_crawls'),
    sa.CheckConstraint('maximum_run_count IS NULL OR maximum_run_count >= 1', name='ck_crawl_schedules_maximum_run_count'),
    sa.CheckConstraint('run_count >= 0', name='ck_crawl_schedules_run_count'),
    sa.ForeignKeyConstraint(['graph_id'], ['crawl_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id', 'name', name='uq_crawl_schedules_graph_name')
    )
    op.create_index('ix_crawl_schedules_due', 'crawl_schedules', ['next_run_at'], unique=False, postgresql_where=sa.text('enabled AND next_run_at IS NOT NULL'))
    op.create_index(op.f('ix_crawl_schedules_graph_id'), 'crawl_schedules', ['graph_id'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_next_run_at'), 'crawl_schedules', ['next_run_at'], unique=False)
    op.create_table('graph_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint('publish_attempts >= 0', name='ck_graph_outbox_publish_attempts'),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_graph_outbox_message_id')
    )
    op.create_index(op.f('ix_graph_outbox_graph_run_id'), 'graph_outbox', ['graph_run_id'], unique=False)
    op.create_index('ix_graph_outbox_ready', 'graph_outbox', ['published_at', 'not_before', 'claim_expires_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('edge_evaluations',
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=False),
    sa.Column('crawl_request_id', sa.UUID(), nullable=False),
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('selection', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_edge_evaluations_status'),
    sa.CheckConstraint('generation >= 1', name='ck_edge_evaluations_generation'),
    sa.ForeignKeyConstraint(['crawl_request_id'], ['crawl_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity')
    )
    op.create_index(op.f('ix_edge_evaluations_crawl_request_id'), 'edge_evaluations', ['crawl_request_id'], unique=False)
    op.create_index(op.f('ix_edge_evaluations_edge_id'), 'edge_evaluations', ['edge_id'], unique=False)
    op.create_index(op.f('ix_edge_evaluations_graph_run_id'), 'edge_evaluations', ['graph_run_id'], unique=False)
    op.create_index('ix_edge_evaluations_run_edge_status', 'edge_evaluations', ['graph_run_id', 'edge_id', 'status'], unique=False)
    op.create_table('graph_admissions',
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('graph_run_id', sa.UUID(), nullable=False),
    sa.Column('crawl_request_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_request_id'], ['crawl_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graph_run_id'], ['graph_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity')
    )
    op.create_index(op.f('ix_graph_admissions_crawl_request_id'), 'graph_admissions', ['crawl_request_id'], unique=False)
    op.create_index(op.f('ix_graph_admissions_graph_run_id'), 'graph_admissions', ['graph_run_id'], unique=False)
    op.create_table(
        'materialization_runs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('mode', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('requested_stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('stages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('projector_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('source_snapshot', sa.BigInteger(), nullable=False),
        sa.Column('catchup_snapshot', sa.BigInteger(), nullable=False),
        sa.Column('catchup_target_snapshot', sa.BigInteger(), nullable=True),
        sa.Column('catchup_stage', sa.Integer(), nullable=False),
        sa.Column('catchup_cursors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('current_stage', sa.Integer(), nullable=False),
        sa.Column('cursors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('destinations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('item_budget', sa.Integer(), nullable=False),
        sa.Column('byte_budget', sa.BigInteger(), nullable=False),
        sa.Column('source_items', sa.BigInteger(), nullable=False),
        sa.Column('source_bytes', sa.BigInteger(), nullable=False),
        sa.Column('output_rows', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.CheckConstraint("mode IN ('backfill', 'rebuild')", name='ck_materialization_runs_mode'),
        sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_materialization_runs_status'),
        sa.CheckConstraint('item_budget >= 1 AND byte_budget >= 1', name='ck_materialization_runs_budgets'),
        sa.CheckConstraint('source_items >= 0 AND source_bytes >= 0 AND output_rows >= 0', name='ck_materialization_runs_counts'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_materialization_runs_status'), 'materialization_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materialization_runs_status'), table_name='materialization_runs')
    op.drop_table('materialization_runs')
    op.drop_index(op.f('ix_graph_admissions_graph_run_id'), table_name='graph_admissions')
    op.drop_index(op.f('ix_graph_admissions_crawl_request_id'), table_name='graph_admissions')
    op.drop_table('graph_admissions')
    op.drop_index('ix_edge_evaluations_run_edge_status', table_name='edge_evaluations')
    op.drop_index(op.f('ix_edge_evaluations_graph_run_id'), table_name='edge_evaluations')
    op.drop_index(op.f('ix_edge_evaluations_edge_id'), table_name='edge_evaluations')
    op.drop_index(op.f('ix_edge_evaluations_crawl_request_id'), table_name='edge_evaluations')
    op.drop_table('edge_evaluations')
    op.drop_index('ix_graph_outbox_ready', table_name='graph_outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index(op.f('ix_graph_outbox_graph_run_id'), table_name='graph_outbox')
    op.drop_table('graph_outbox')
    op.drop_index(op.f('ix_crawl_schedules_next_run_at'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_graph_id'), table_name='crawl_schedules')
    op.drop_index('ix_crawl_schedules_due', table_name='crawl_schedules', postgresql_where=sa.text('enabled AND next_run_at IS NOT NULL'))
    op.drop_table('crawl_schedules')
    op.drop_index(op.f('ix_crawl_requests_status'), table_name='crawl_requests')
    op.drop_index(op.f('ix_crawl_requests_source_edge_id'), table_name='crawl_requests')
    op.drop_index('ix_crawl_requests_runnable', table_name='crawl_requests')
    op.drop_index('ix_crawl_requests_run_node_status', table_name='crawl_requests')
    op.drop_index(op.f('ix_crawl_requests_not_before'), table_name='crawl_requests')
    op.drop_index(op.f('ix_crawl_requests_node_id'), table_name='crawl_requests')
    op.drop_index(op.f('ix_crawl_requests_graph_run_id'), table_name='crawl_requests')
    op.drop_table('crawl_requests')
    op.drop_index(op.f('ix_crawl_graph_edges_target_node_id'), table_name='crawl_graph_edges')
    op.drop_index(op.f('ix_crawl_graph_edges_source_node_id'), table_name='crawl_graph_edges')
    op.drop_index(op.f('ix_crawl_graph_edges_graph_id'), table_name='crawl_graph_edges')
    op.drop_table('crawl_graph_edges')
    op.drop_index(op.f('ix_graph_runs_trigger_schedule_id'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_status'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_not_before'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_graph_id'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_deadline_at'), table_name='graph_runs')
    op.drop_index('ix_graph_runs_active', table_name='graph_runs', postgresql_where=sa.text("status IN ('queued', 'running', 'paused')"))
    op.drop_table('graph_runs')
    op.drop_index('ix_domain_policies_enabled', table_name='domain_policies')
    op.drop_table('domain_policies')
    op.drop_index('ix_crawl_policies_host', table_name='crawl_policies')
    op.drop_index('ix_crawl_policies_enabled', table_name='crawl_policies')
    op.drop_table('crawl_policies')
    op.drop_constraint('fk_crawl_graphs_root_node', 'crawl_graphs', type_='foreignkey')
    op.drop_index(op.f('ix_crawl_graph_nodes_graph_id'), table_name='crawl_graph_nodes')
    op.drop_table('crawl_graph_nodes')
    op.drop_table('crawl_graphs')
    # ### end Alembic commands ###
