"""Public Atlas SQL compiler SDK."""

from catalogue.compiler import (
    BoundParameter,
    CatalogueDefinitionPurpose,
    CatalogueMetadataSnapshot,
    CatalogueLintDiagnostic,
    CatalogueQueryError,
    CatalogueStatementKind,
    ClassifiedCatalogueStatement,
    ColumnStatistics,
    FullMaterializationPurpose,
    GraphEdgePurpose,
    InteractiveQueryPurpose,
    KeyedMaterializationPurpose,
    ManagedTableMetadata,
    PartitionColumn,
    ScalarMacroDefinition,
    ScalarFunctionDefinition,
    SqlCompilationOutcome as CompilationOutcome,
    SqlCompilationPurpose as CompilationPurposeName,
    TableMacroDefinition,
    ViewDefinition,
    classify_catalogue_statement,
    classify_select,
    graph_edge_uses_catalogue,
    lint_catalogue_statement,
    lint_select,
)

from .compiler import AtlasCompiler, AtlasCompilerUnavailable
from .models import (
    AnalysisComparison,
    AnalysisMetrics,
    AnalysisOperator,
    AnalysisOperatorDifference,
    AnalysisPlanOutcome,
    AnalysisPlanStatus,
    AnalysisResult,
    AppliedRewrite,
    CompilationDiagnostic,
    CompilationResult,
    CompilationEstimate,
    DefinitionDependency,
    ScanEstimate,
)

__all__ = [
    "AppliedRewrite",
    "AnalysisComparison",
    "AnalysisMetrics",
    "AnalysisOperator",
    "AnalysisOperatorDifference",
    "AnalysisPlanOutcome",
    "AnalysisPlanStatus",
    "AnalysisResult",
    "AtlasCompiler",
    "AtlasCompilerUnavailable",
    "BoundParameter",
    "CatalogueMetadataSnapshot",
    "CatalogueLintDiagnostic",
    "CatalogueQueryError",
    "CatalogueStatementKind",
    "ClassifiedCatalogueStatement",
    "CatalogueDefinitionPurpose",
    "CompilationDiagnostic",
    "CompilationEstimate",
    "CompilationOutcome",
    "CompilationPurposeName",
    "CompilationResult",
    "DefinitionDependency",
    "ColumnStatistics",
    "FullMaterializationPurpose",
    "GraphEdgePurpose",
    "InteractiveQueryPurpose",
    "KeyedMaterializationPurpose",
    "ManagedTableMetadata",
    "PartitionColumn",
    "ScalarMacroDefinition",
    "ScalarFunctionDefinition",
    "ScanEstimate",
    "TableMacroDefinition",
    "ViewDefinition",
    "classify_catalogue_statement",
    "classify_select",
    "graph_edge_uses_catalogue",
    "lint_catalogue_statement",
    "lint_select",
]
