import type { Metadata } from "next"
import { pageMetadata } from "@/lib/seo"
import Link from "next/link"
import { ArrowUpRight, Files, Columns3, ArrowRight } from "lucide-react"

export const metadata: Metadata = pageMetadata("/about", "The idea behind Periplus", "Periplus is a structured, analytical lens into the web: shared source structure, datasets you define, and SQL that makes your interpretation inspectable.")

export default function AboutPage() {
  return <main className="about-page">
    <header className="flex flex-wrap items-baseline justify-between gap-2 py-6"><h1 className="text-xl font-medium">About Periplus</h1><p className="text-sm text-muted-foreground">Project background, access, and data use.</p></header><nav className="flex flex-wrap gap-5 pb-8" aria-label="On this page"><a href="#vision">The perspective</a><a href="#meaning">Your dataset</a><a href="#agents">People & agents</a><a href="#foundation">A shared foundation</a><a href="#access">Access & data use</a></nav>

    <section id="vision" className="about-section"><span className="eyebrow">01 / The perspective</span><div><h2>The web holds more<br />than pages to read.</h2><p>Book listings, publication histories, directories, and networks of links are all waiting inside web pages. A dataset begins when you decide what each row represents.</p><p>Periplus keeps the source structure so the same pages can answer different questions—even ones nobody anticipated when they were collected.</p></div></section>

    <figure className="about-concept" aria-label="Shared pages become datasets through your SQL"><div><Files aria-hidden="true" /><strong>Shared pages</strong><span>Text, links, and HTML</span></div><ArrowRight aria-hidden="true" /><div><code>SELECT …</code><strong>Your interpretation</strong><span>Fields, sources, and rules</span></div><ArrowRight aria-hidden="true" /><div><Columns3 aria-hidden="true" /><strong>Your dataset</strong><span>Rows with their sources</span></div><figcaption>The same material. New questions. A method you can inspect.</figcaption></figure>

    <section id="meaning" className="about-section"><span className="eyebrow">02 / Your dataset</span><div><h2>Keep the structure.<br />Choose the meaning.</h2><p>Periplus is a shared web databank that preserves elements, text, attributes, and links. You decide what they mean in your dataset.</p><p>A heading might become a book title, an organisation name, or a topic. You decide which interpretation fits your dataset. SQL expresses that decision, combines the relevant material, and produces your schema.</p><p>The result is both a dataset and an inspectable method for producing it. Example datasets demonstrate what you can build; the shared infrastructure lets you define something of your own.</p></div></section>

    <section id="agents" className="about-section"><span className="eyebrow">03 / People & agents</span><div><h2>Start with an idea.<br />Make the method explicit.</h2><p>Start in Discover when you have a question or want to see what the available data can support. Review the findings and sources, whether or not you need a dataset.</p><p>Use Build when you have a dataset specification. Describe your schema, edit it directly, or import a saved Periplus draft. The builder maps the corpus to your columns, types, and nullability, and reports where the results fall short. You retain control over what a row means and which sources belong.</p><p>SQL makes those choices visible and reusable. As your needs change, you can revise the definition and produce a different view of the same material.</p><div className="about-actions"><Link className="story-link" href="/discover">Discover data <ArrowUpRight /></Link><Link className="story-link" href="/build">Build a dataset <ArrowUpRight /></Link><Link className="story-link" href="/docs#recipe">SQL extraction guide <ArrowUpRight /></Link></div></div></section>

    <section id="foundation" className="about-section"><span className="eyebrow">04 / A shared foundation</span><div><h2>Shared data.<br />More possibilities.</h2><p>A useful source can serve many datasets. A new query can reveal value in pages already collected. Periplus aims to make that foundation richer and more useful over time, through shared structure, broader coverage, and methods people can build on.</p><p>That is the direction, and today’s corpus is small. What you can build depends on the sources and observations available. <Link href="/coverage#coverage">Explore current coverage</Link> or <Link href="/coverage">request broader coverage</Link> to help shape where it grows.</p><p>For the mechanics—how pages become tables, how observations relate to content, and how to write your extraction—start with the <Link href="/docs">documentation</Link>.</p></div></section>

    <section id="access" className="about-section"><span className="eyebrow">05 / Access & use</span><div><h2>Free to explore.<br />Clear about what you get.</h2><p>Periplus is free to explore and requires no account. The <Link href="/docs">core documentation</Link> covers collection, SQL extraction, and query-service limits.</p><h3>Questions, queries, and privacy</h3><p>Periplus logs executed SQL, parameters, outcomes, and timings to debug and improve the service. Discover and Build send your conversation text and sampled query results to the model provider. Running SQL directly in the SQL console does not use an AI model.</p><p>Conversations are held in the browser and disappear on reload; this does not mean server query logs disappear. Workspace links can include questions, SQL, parameters, and dataset specifications in the destination URL. Keep secrets and private information out of these inputs. Submitted collection URLs and collected data are public.</p><h3>Using collected content</h3><p>“Public” describes access to Periplus. Periplus has not published a blanket reuse licence for third-party content or formal service terms. Do not interpret the availability of a row or an export as permission to redistribute the underlying content. Contact us about your intended use before depending on Periplus for redistribution or production.</p><p>Formal privacy and data-use policies are not published yet. For questions about stored information, source content, or removal requests, contact <a href="mailto:ekku.leivonen@elei.io">ekku.leivonen@elei.io</a>.</p><h3>Help improve Periplus</h3><p>Send a dataset you want to build, a dataset query worth sharing, or a result that needs attention. Include the query reference when reporting a problem so we can investigate the same execution.</p><div className="about-actions"><a className="story-link" href="mailto:ekku.leivonen@elei.io?subject=Periplus%20feedback">Send feedback <ArrowUpRight /></a><Link className="story-link" href="/build">Build a dataset <ArrowUpRight /></Link></div></div></section>
  </main>
}
