import { coverageSql } from "@/lib/datasets"
import { sqlDraftLink } from "@/lib/schema-reference"
import type { Metadata } from "next"
import { pageMetadata } from "@/lib/seo"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"

export const metadata: Metadata = pageMetadata("/about", "Why Periplus exists", "Periplus grew out of rebuilding data pipelines for every new idea. Preserve the pages, explore with SQL, and share a corner of the web with other curious data people.")

export default function AboutPage() {
  return <main className="about-page">
    <header className="flex flex-wrap items-baseline justify-between gap-2 py-6"><h1 className="text-xl font-medium">About Periplus</h1><p className="text-sm text-muted-foreground">For people who see the web as something to explore.</p></header>
    <nav className="flex flex-wrap gap-5 pb-8" aria-label="On this page"><a href="#vision">Where it started</a><a href="#preserve">Keep the source</a><a href="#questions">Follow a question</a><a href="#foundation">Who it’s for</a><a href="#access">Access & data use</a></nav>
    <section id="vision" className="about-section"><span className="eyebrow">01 / Where it started</span><div><h2>Another idea.<br />Another data pipeline.</h2><p>Periplus grew out of years of small data and machine learning projects. Each began with a suspicion that some corner of the internet might contain an interesting signal.</p><p>Before the idea could be tested came the crawler, the parsers and the extraction jobs. Sometimes the resulting data revealed a better question. Sometimes it revealed a missing field or a mistake in the parser. Sometimes the idea simply wasn’t worth pursuing.</p><p>The next project brought another pipeline. A website changed its layout, and an existing parser needed fixing. Too much of the work had to be repeated before the interesting part could begin.</p><p>Periplus is an attempt to keep more of that work useful, across projects and between people.</p></div></section>
    <section id="preserve" className="about-section"><span className="eyebrow">02 / Keep the source</span><div><h2>Leave room to<br />change your mind.</h2><p>An early extraction is a decision about what matters. It is easy to discard something that turns out to be useful later.</p><p>Periplus preserves the captured HTML and makes its text, structure and links available to query. You can return to the page as it was captured, examine its context and extract different fields as your understanding develops.</p><p>The source remains separate from the interpretation. A new question can use the same material without inheriting every assumption of the first project.</p></div></section>
    <section id="questions" className="about-section"><span className="eyebrow">03 / Follow a question</span><div><h2>You don’t need the final<br />question to get started.</h2><p>A directory, a collection of company websites, an unfamiliar set of publications: sometimes a source looks interesting before there is a clear project in mind.</p><p>SQL gives you a way to explore it. Search the text, pull out headings, follow links between pages and compare their destinations. Inspect the section around a link to understand its context. Change the query and see what else emerges.</p><p>When a question becomes worth returning to, repeated captures give you dated observations to compare. The same query can help investigate how a corner of the web is changing.</p><p>Start in the SQL console. Write a query or use Ask SQL to help draft one, then run it and export the results.</p><div className="about-actions"><Link className="story-link" href="/sql">Explore with SQL <ArrowUpRight /></Link></div></div></section>
    <section id="foundation" className="about-section"><span className="eyebrow">04 / Who it’s for</span><div><h2>For people who think:<br />“I wonder what’s in there.”</h2><p>Periplus is for curious data people: researchers, developers, analysts and hobbyists who enjoy finding a source, looking for patterns and seeing whether an idea holds up.</p><p>The collection is shaped by the people using it. Bring websites you want to investigate, and their captured pages become available to others too. Someone else may find a signal you weren’t looking for, or use your starting point for an entirely different project.</p><p>Over time, the ambition is to make interesting queries and datasets easier to share as well, so people can build on each other’s investigations alongside the source material.</p><p>Bring a question, a hunch, or a corner of the web you think is worth a look.</p><div className="about-actions"><Link className="story-link" href={sqlDraftLink(coverageSql)}>Explore shared websites <ArrowUpRight /></Link><Link className="story-link" href="/coverage">Add your sources <ArrowUpRight /></Link></div></div></section>
    <section id="access" className="about-section"><span className="eyebrow">05 / Access & use</span><div><h2>Try the public preview.<br />Understand how data is used.</h2><p>Periplus is free to explore and requires no account. The <Link href="/docs">core documentation</Link> covers collection, SQL extraction, and query-service limits.</p><h3>Questions, queries, and privacy</h3><p>Periplus logs executed SQL, parameters, outcomes, and timings to debug and improve the service. Ask SQL sends your request, editor context and sampled results from its exploration queries to the model provider. Running SQL directly in the SQL console does not use an AI model.</p><p>Conversations are held in the browser and disappear on reload; this does not mean server query logs disappear. SQL links can include queries and parameters in the destination URL. Keep secrets and private information out of these inputs. Submitted collection URLs and collected data are public.</p><h3>Using collected content</h3><p>“Public” describes access to Periplus. Periplus has not published a blanket reuse licence for third-party content or formal service terms. Do not interpret the availability of a row or an export as permission to redistribute the underlying content. Contact us about your intended use before depending on Periplus for redistribution or production.</p><p>Formal privacy and data-use policies are not published yet. For questions about stored information, source content, or removal requests, contact <a href="mailto:ekku.leivonen@elei.io">ekku.leivonen@elei.io</a>.</p><h3>Help shape Periplus</h3><p>Tell us what you were trying to find, which sources you needed, and where the results helped or fell short. Include the query reference when reporting a problem so we can investigate the same execution.</p><div className="about-actions"><a className="story-link" href="mailto:ekku.leivonen@elei.io?subject=Periplus%20feedback">Send feedback <ArrowUpRight /></a><Link className="story-link" href="/sql">Explore with SQL <ArrowUpRight /></Link></div></div></section>
  </main>
}
