import { DatabaseZapIcon, RefreshCwIcon, Trash2Icon } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { useDropMaterializedView, useMaterializedViews, useRefreshMaterializedView } from "@/hooks/use-materialized-views"
export function MaterializedViewsPage() {
  const query = useMaterializedViews(); const refresh = useRefreshMaterializedView(); const drop = useDropMaterializedView(); const views = query.data?.items ?? []
  return <div className="flex min-h-0 w-full flex-col gap-4"><div className="flex items-center gap-2"><DatabaseZapIcon className="size-4 text-primary" /><h1 className="text-lg font-medium">Materialized Views</h1><Badge variant="outline">{views.length}</Badge></div><Table containerClassName="min-h-0 flex-1 rounded-xl border bg-card/80"><TableHeader><TableRow><TableHead>Table</TableHead><TableHead>Source</TableHead><TableHead>Rows</TableHead><TableHead>Columns</TableHead><TableHead>Refreshed</TableHead><TableHead className="w-40">Actions</TableHead></TableRow></TableHeader><TableBody>{views.map((view) => <TableRow key={view.id}><TableCell><div className="font-medium">{view.display_name}</div><div className="font-mono text-[10px] text-muted-foreground">{view.qualified_name}</div></TableCell><TableCell>{view.query_name} · v{view.query_revision}</TableCell><TableCell>{view.row_count.toLocaleString()}</TableCell><TableCell>{view.columns.length}</TableCell><TableCell>{new Date(view.last_refreshed_at).toLocaleString()}</TableCell><TableCell><div className="flex gap-1"><Button size="icon-sm" variant="outline" aria-label="Full refresh" onClick={() => refresh.mutate(view)} disabled={refresh.isPending}><RefreshCwIcon /></Button><Button size="icon-sm" variant="destructive" aria-label="Drop materialized view" onClick={() => { if (window.confirm(`Drop ${view.qualified_name}?`)) drop.mutate(view) }} disabled={drop.isPending}><Trash2Icon /></Button></div></TableCell></TableRow>)}{!query.isLoading && views.length === 0 && <TableRow><TableCell colSpan={6} className="h-28 text-center text-muted-foreground">Create one from a saved query revision.</TableCell></TableRow>}</TableBody></Table></div>
}
