export const catalogueTables = {
  artifacts: [
    "artifact_id",
    "object_key",
    "size_bytes",
    "response_media_type",
    "detected_media_type",
    "detector_name",
    "detector_version",
    "detection_confidence",
    "first_seen_at",
  ],
  documents: [
    "document_id",
    "object_key",
    "content_type",
    "encoding",
    "size_bytes",
    "compressed_size_bytes",
    "compression",
    "dom_schema_version",
    "parser_name",
    "parser_version",
    "parser_options_hash",
    "element_count",
    "first_seen_at",
  ],
  elements: [
    "document_id",
    "element_index",
    "parent_index",
    "subtree_end_index",
    "depth",
    "tag",
    "namespace_uri",
    "attributes",
    "text_direct",
    "text_tail",
  ],
  crawls: [
    "crawl_id",
    "document_id",
    "artifact_id",
    "graph_id",
    "graph_run_id",
    "graph_node_id",
    "source_crawl_id",
    "source_edge_id",
    "requested_url",
    "url",
    "scheme",
    "host",
    "port",
    "registrable_domain",
    "path",
    "query",
    "started_at",
    "completed_at",
    "content_captured_at",
    "status_code",
    "response_media_type",
    "policy_schema_version",
    "effective_policy_hash",
    "effective_policy",
    "outcome",
    "failure_code",
    "failure_stage",
    "failure_retryable",
    "failure_detail",
  ],
  crawl_attempts: [
    "crawl_id",
    "attempt_number",
    "started_at",
    "completed_at",
    "requested_url",
    "url",
    "status_code",
    "response_media_type",
    "outcome",
    "failure_code",
    "retry_after_seconds",
  ],
  crawl_steps: [
    "crawl_id",
    "attempt_number",
    "step_ordinal",
    "method",
    "method_version",
    "config_hash",
    "config_json",
    "started_at",
    "duration_ms",
    "iterations",
    "stop_reason",
    "before_element_count",
    "after_element_count",
    "before_text_chars",
    "after_text_chars",
    "before_link_count",
    "after_link_count",
    "before_scroll_height",
    "after_scroll_height",
  ],
} as const

export const catalogueFunctions = [
  {
    label: "macros.resolve_url",
    type: "function",
    detail: "macros.resolve_url(source, href) → absolute URL",
  },
  {
    label: "macros.normalize_url",
    type: "function",
    detail: "macros.normalize_url(value) → normalized HTTP(S) URL or NULL",
  },
  {
    label: "macros.url_parts",
    type: "function",
    detail: "macros.url_parts(value) → URL component struct",
  },
  {
    label: "macros.get_attribute",
    type: "function",
    detail: "macros.get_attribute(attributes, name) → value or NULL",
  },
  {
    label: "macros.has_attribute",
    type: "function",
    detail: "macros.has_attribute(attributes, name) → boolean",
  },
  {
    label: "macros.has_text",
    type: "function",
    detail: "macros.has_text(value) → contains non-whitespace text",
  },
  {
    label: "macros.text_content",
    type: "function",
    detail: "macros.text_content(document_id, element_index) → DOM textContent",
  },
  {
    label: "macros.inner_html",
    type: "function",
    detail: "macros.inner_html(document_id, element_index) → canonical child HTML",
  },
  {
    label: "macros.readable_text",
    type: "function",
    detail:
      "macros.readable_text(document_id, element_index) → normalized reading text",
  },
] as const
