export const catalogueTables = {
  documents: [
    "document_id",
    "html_sha256",
    "html_object_key",
    "html_content_type",
    "html_encoding",
    "html_size_bytes",
    "html_compressed_size_bytes",
    "compression",
    "dom_schema_version",
    "parser_name",
    "parser_version",
    "parser_options_hash",
    "element_count",
    "created_at",
  ],
  elements: [
    "document_id",
    "element_index",
    "parent_index",
    "subtree_end_index",
    "depth",
    "tag",
    "namespace_uri",
    "attributes",
    "text_direct",
    "text_tail",
  ],
  crawls: [
    "crawl_id",
    "document_id",
    "graph_id",
    "graph_run_id",
    "graph_node_id",
    "crawl_request_id",
    "source_crawl_id",
    "source_edge_id",
    "requested_url",
    "normalized_url",
    "final_url",
    "page_url",
    "url_scheme",
    "url_host",
    "url_port",
    "url_registrable_domain",
    "url_path",
    "url_query",
    "captured_at",
    "status_code",
    "duration_ms",
    "input_json",
    "input_hash",
    "crawl_policy_id",
    "crawl_policy_revision",
    "warnings_json",
    "errors_json",
  ],
} as const

export const catalogueFunctions = [
  {
    label: "resolve_url",
    type: "function",
    detail: "resolve_url(source, href) → absolute URL",
  },
  {
    label: "get_attribute",
    type: "function",
    detail: "get_attribute(attributes, name) → value or NULL",
  },
  {
    label: "has_attribute",
    type: "function",
    detail: "has_attribute(attributes, name) → boolean",
  },
  {
    label: "has_text",
    type: "function",
    detail: "has_text(value) → contains non-whitespace text",
  },
  {
    label: "text_content",
    type: "function",
    detail: "text_content(document_id, element_index) → DOM textContent",
  },
  {
    label: "inner_html",
    type: "function",
    detail: "inner_html(document_id, element_index) → canonical child HTML",
  },
  {
    label: "readable_text",
    type: "function",
    detail: "readable_text(document_id, element_index) → normalized reading text",
  },
] as const
